### ISSUE TITLE
Support bypassing Auto-Register

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/edd-free-downloads#103]
A customer brought up that FD creates a user account if auto-register is enabled. We should (and I thought we did) allow bypassing account creation.

**Comment by mintplugins** [comment]
This is working for me here. When bypass is enabled, no user account is auto created through Auto Register. When disabled, users are auto created. 

I have a pet peeve with double-negative checkboxes though. Could this perhaps be changed to "Allow Auto-Registration" and have it be checked by default?

**Comment by ghost1227** [comment]
@mintplugins Not inclined to... if you look through the FD settings, most of the checkboxes are disabling things. Plus, we're not allowing something that's normally not allowed, we're bypassing the normal operation.

**Comment by ghost1227** [comment]
In other words, if we do that for one, it'd make sense to do it for all.. which would require an upgrade routine since most are long-standing options. Seems seriously like overkill for a pet peeve 😉

**Comment by mintplugins** [comment]
Dang... :P

**Comment by ghost1227** [comment]
lol Generally I agree that enabling sounds better than disabling. But given we're disabling an existing feature established by another plugin, i stand by my original wording.

**Comment by mintplugins** [comment]
I hear you. Sounds good to me. - though I'm going to pout over in the corner for a bit about it.
