### ISSUE TITLE
Variable Prices are not working

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-free-downloads#107]
If you have a product with a variable price that is free, it fails with error message:

"An internal error has occurred, please try again or contact support."

I have tracked this down to line 126 of download-actions.php. For some reason $_POST['edd_free_download_price_id'] is empty so on line 123 the variable pricing lines are not run:

https://github.com/easydigitaldownloads/edd-free-downloads/blob/master/includes/download-actions.php#L120

Confirmed by @SDavisMedia

**Comment by mintplugins** [comment]
@ghost1227

**Comment by ghost1227** [comment]
@mintplugins Huh... that was tested repeatedly before it went live. That's super odd..

**Comment by mintplugins** [comment]
Working now! Thanks @ghost1227

**Comment by ghost1227** [comment]
NP!
