### ISSUE TITLE
Select which emails will be disabled

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/edd-free-downloads#118]
It would be nice to select which emails are disabled with the "Disable Emails" setting. If you enable it, both the customer and admin email notification are disabled. I'd like the customer to still receive their purchase receipt, but prevent the email coming through to the admin.

**Comment by dannyb195** [comment]
@cklosowski and I decided that leaving the current setting while adding a "disable admin emails" option is the correct path to preserve backwards compat on this issue. This is in progress at https://github.com/easydigitaldownloads/edd-free-downloads/compare/release/2.2.0...issue/93?expand=1

**Comment by cklosowski** [comment]
There's 1 problem I'm seeing.

this allows you to disable all emails, or just the admin email. We need a 3rd option, to disable the customer email but allow the admin email.

We should also probably update the setting name of `Disabled Emails` to read `Disable Purchase Confirmation`

And the admin option to `Disable Admin Sales Notifications` to follow what EDD Core calls those.

**Comment by cklosowski** [comment]
That may sound confusing, we don't need another setting, just the logic needs to shift a little to allow triggering the admin notice without the purchase confirmation notice.

**Comment by dannyb195** [comment]
@cklosowski I think we *do* need an additional option in this case:

1. Send everyone an email (already taken care of)
2. Send on only the custom an email (as seen in PR #212 )
3. Send only admins a purchase confirmation (not yet done - which is what we are talking about right now)

**Comment by cklosowski** [comment]
I disagree, two options is sufficient to do all the checks necessary.

By changing the title of the existing option to only be for the customer purchase confirmation, we can change the logic behind it to also check if the admin notification should still be sent.

Three options seems overkill to stop 2 emails.

**Comment by dannyb195** [comment]
@cklosowski if I understand you correctly you propose the following options:

1. "Dont send to customer"
2. "Dont send to admins"

is this correct?

**Comment by cklosowski** [comment]
Correct, most people who use the existing option, use it to stop the purchase confirmation from getting sent to customers, so by simply converting that setting to mean customers only, we can use some of the existing filters in EDD to what we need.

**Comment by dannyb195** [comment]
PR at https://github.com/easydigitaldownloads/edd-free-downloads/pull/212/files

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs this is ready for more testing.

**Comment by mintplugins** [comment]
Pretending I'm a user, I'm having trouble understanding these settings at first glance:

Could we clarify this a bit better? 
`Disable Purchase Confirmation`
`Check to disable purchase emails for non-admin users for free products.`

Purchase confirmation to whom? The customer? Every non-admin user? I'm confused. 

Also there's a spelling mistake here (notifications):
`Disable Admin Sales Notifications`
`Check to disable purchase emails notifiations for Admin user for free products.`

Additionally, could we clarify this one better as well? I propose:

`Checking this will disable the purchase email notifications which get sent to all Admin users when a free product is purchased.`

**Comment by cklosowski** [comment]
The first should not reference non-admin. It's just simply our normal
purchase confirmation email.

**Comment by mintplugins** [comment]
Tested disabling both, and each option individually - all work as expected 👍
