### ISSUE TITLE
Sprinkle some do_actions into the modal code

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/edd-free-downloads#120]
It would be nice to have some `do_action`'s carefully sprinkled around the modal HTML. 

Personally, I'd like one where the notes are so I can add a conditional message based on whether the user is logged-in or not (or other conditionals). I think this would be handy. Perhaps the usual 1 at top, one at bottom, and one for notes or anywhere else you see fit.

**Comment by ghost1227** [comment]
@sumobi I did add a few actions during the 2.0.0 update, plus it's now fully templated... is this still needed?

**Comment by cklosowski** [comment]
Let's handle this in #152, with the modal rewrite.

**Comment by dannyb195** [comment]
This should be taken care of in #206 via
https://github.com/easydigitaldownloads/edd-free-downloads/pull/206/commits/f9501496db95228cb84ee7b240781f4fb8424054

and

https://github.com/easydigitaldownloads/edd-free-downloads/pull/206/commits/eb0c0d26498123a30f4634830e60da2584acd767
