### ISSUE TITLE
Download fails if query string exists in URL and "bypass if logged in" is enabled

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/edd-free-downloads#122]
If the URL already contains a query string (i.e. UTM parameters often added via emails and doc links), the free download fails when:
- The user is logged in
- "Bypass if logged in" is enabled from settings

Spotted by a customer and I've also replicated. To replicate:
1. Make sure "bypass if logged in" is enabled
2. Make sure you're logged into the site
3. Go to a page where there's a free download and add a query string to the URL, such as `?something=true`
4. Click to download the file. 

The page will reload, no file is downloaded and the URL will have double `?`'s like this:

```
?something=true?edd_action=free_downloads_process_download&download_id=84287&price_ids=
```

**Comment by dannyb195** [comment]
A note on reproducing per 3rd point in the initial comment. You must add the query string, _then_ reload the page with the new fake query string to duplicate this issue.

**Comment by dannyb195** [comment]
PR at https://github.com/easydigitaldownloads/edd-free-downloads/pull/208/files

**Comment by pippinsplugins** [comment]
PR works great, merged!
