### ISSUE TITLE
Activating free downloads shouldn't change the button width

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/edd-free-downloads#123]
When the free downloads extension is installed, it shouldn't change the download button width.

---

A standard free download in EDD (2016 theme):

![screen shot 2016-10-16 at 2 00 03 am](https://cloud.githubusercontent.com/assets/52581/19410291/972c036a-9344-11e6-9cd6-28f0a5a72efe.png)

---

The same free download but with Free Downloads active:

![screen shot 2016-10-16 at 2 00 17 am](https://cloud.githubusercontent.com/assets/52581/19410290/972bd0f2-9344-11e6-9df5-6d41eb543ffd.png)

---

This is clearly `display: block` vs `display: inline-block` voodoo magic. Perhaps the `edd_purchase_submit_wrapper` class is missing on the parent div or something. What I can see however is:

```
.edd-free-download-single {
    display: inline-block !important;
}
```

Let's get rid of the `inline-block` here for starters. And there's no reason why `!important` should ever be used.

**Comment by ghost1227** [comment]
@sumobi This is something that me and @SDavisMedia discussed during the 2.0.0 update. I believe it's already resolved... can you verify that?

**Comment by dannyb195** [comment]
Test Theme: 2017

Without Free Downloads active:
<img width="557" alt="screen shot 2017-10-12 at 3 45 10 pm" src="https://user-images.githubusercontent.com/247887/31518353-9770bc16-af64-11e7-8782-6c3e5e0e2ba2.png">


With Free Downloads active:
<img width="549" alt="screen shot 2017-10-12 at 3 45 30 pm" src="https://user-images.githubusercontent.com/247887/31518509-18f89dbc-af65-11e7-8ba8-eb69b90d137b.png">

@cklosowski  I think this issue can be closed
