### ISSUE TITLE
Focus trap on modal window

### ISSUE THREAD

**Issue by samikeijonen** [easydigitaldownloads/edd-free-downloads#124]
First, great job on the plugin!

I noticed minor accessibility issue when opening the modal window using keyboard. Focus is not moved inside to modal window. It should probably move to first focusable element like email field.

Also focus doesn't stay inside the modal window (well because it's not moved inside in the first place:) before modal is closed.

Here is good example of [accessible modal window](http://edenspiekermann.github.io/a11y-dialog/).

I can work on this but I have so little extra time at the moment :slightly_smiling_face:

**Comment by cklosowski** [comment]
@dannyb195 Let's see if your rewrite can do this for us in #152. Now that we've dropped reliance on a modal library, and we're running most of the JS, we can do this much easier I believe.

**Comment by dannyb195** [comment]
this should be address via https://github.com/easydigitaldownloads/edd-free-downloads/pull/206/commits/076cb2f0da5b273986bcd66b70574a4af4f46839

**Comment by dannyb195** [comment]
PR comment, https://github.com/easydigitaldownloads/edd-free-downloads/commit/076cb2f0da5b273986bcd66b70574a4af4f46839#commitcomment-25038694

**Comment by dannyb195** [comment]
moving focus to first input field per https://github.com/easydigitaldownloads/edd-free-downloads/pull/206#commitcomment-25038694

via https://github.com/easydigitaldownloads/edd-free-downloads/pull/206/commits/3af03103e0d9db60e420cb3e5417da8f43c593a1

**Comment by cklosowski** [comment]
This is working fine in #206 (#152)
