### ISSUE TITLE
Variable products it not working with latest EDD update

### ISSUE THREAD

**Issue by mehedi-sharif** [easydigitaldownloads/edd-free-downloads#125]
Just updated latest EDD and the variable product is not working.
Here is the live url : http://www.furioustheme.com/products/box-bootstrap-portfolio-template/
Everything is working with my previous version of EDD 2.6.10 in my localhost. 
Hope you people will update this issue soon.
BTW I have purchased the license .
Thanks

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
