### ISSUE TITLE
Bypass If Logged In setting doesn't work with variable pricing

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-free-downloads#131]
If you have a variable pricing product where one option is free, triggering Free Downloads, you get both buttons at the same time:

<img width="374" alt="screenshot 2016-11-22 09 34 49" src="https://cloud.githubusercontent.com/assets/2359131/20534696/035aa248-b097-11e6-8eb2-0cbbc69928f9.png">

And you get this wp_die error when you try to download the free product:

`You have tried to cheat. Play nice please.`

**Comment by SDavisMedia** [comment]
Hasn't this been addressed already? Seems to be fine now.

**Comment by pippinsplugins** [comment]
If you can't replicate, let's close as fixed.

**Comment by SDavisMedia** [comment]
Seems good to go.
