### ISSUE TITLE
[edd_free_download] shows popup modal even if logged in

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-free-downloads#132]
If you have "Bypass If Logged In" checked and are using the edd_free_download shortcode, the modal still appears. 

This only happens for buttons output using the shortcode. Normal Free Downloads buttons correctly download the product without the popup for logged in users.

**Comment by dannyb195** [comment]
This should also be taken care of via https://github.com/easydigitaldownloads/edd-free-downloads/pull/206 . @cklosowski I think we can close this upon approval of PR #206

**Comment by cklosowski** [comment]
I agree, with #152, let's leave this open, but re-test this once we have #152 merged in and tested.
