### ISSUE TITLE
Add form customization

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/edd-free-downloads#14]
Might be worth while to add a form customizer?

https://secure.helpscout.net/conversation/97137128/10757

**Comment by pippinsplugins** [comment]
:+1:

**Comment by ghost1227** [comment]
For the record, form builders SUCK

**Comment by pippinsplugins** [comment]
From a development perspective or usability?

**Comment by ghost1227** [comment]
Both I guess, but I meant from a dev perspective

**Comment by mindctrl** [comment]
@ghost1227 would this allow people to show a opt-in/out button for the newsletter? We've had several requests to have a checkbox on the modal.

**Comment by ghost1227** [comment]
Forms are now template based and can be overridden.

**Comment by pippinsplugins** [comment]
@ghost1227 can you please make sure that all issues get milestoned so that we can more easily know when items were taken care of down the road?

**Comment by ghost1227** [comment]
Sure
