### ISSUE TITLE
Improve notes UX

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/edd-free-downloads#140]
Currently, notes load through AJAX which can cause a slight delay on the frontend. Let's find a better way to handle this so that the delay doesn't happen, or happens more gracefully!

**Comment by SDavisMedia** [comment]
Nice and snappy now. :+1:

**Comment by ignascb2** [comment]
I have downloaded the file but i dont see any difference. May I be doing something wrong?

**Comment by SDavisMedia** [comment]
@ignascb2 if you are having issues, please open a support ticket here: https://easydigitaldownloads.com/support/
