### ISSUE TITLE
Pass purchase key to redirects

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/edd-free-downloads#145]
Since we don't currently have the ability to do auto-download _and_ redirect, @SDavisMedia has requested a way of bringing purchase data into the redirect page. I'd like to add a full shortcode-based system to allow insertion of all purchase-related data to the redirect page.

**Comment by SDavisMedia** [comment]
I think this would be pretty cool if kept simple enough. Could also be considered for core, I'd think. But that's a different conversation.

**Comment by cklosowski** [comment]
For now, what if we just simply appended the 'purchase key' to the redirect? That way someone could pull that data in a custom plugin. Would that achieve what we want?

**Comment by dannyb195** [comment]
Please note the purchase_key was added here, https://github.com/easydigitaldownloads/edd-free-downloads/blame/release/2.2.0/includes/download-actions.php#L299, possibly rendering this issue moot.

**Comment by cklosowski** [comment]
I'm updating this issue title, after some discussions with @SDavisMedia. The purchase key would be more than enough for someone to get custom purchase data into a custom redirect with a template file. It'll be included on any redirects performed by the new modal, except for auto-download

**Comment by SDavisMedia** [comment]
Yup! That'll do!

**Comment by cklosowski** [comment]
Sweet we'll close this along side #152 then.
