### ISSUE TITLE
Make Auto-Download work with files hosted on AmazonS3

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-free-downloads#147]
Currently, if you use the Auto-Download feature in Free Downloads and your files are hosted on AmazonS3, it redirects the user to a 404 page.

**Comment by mintplugins** [comment]
https://secure.helpscout.net/conversation/293820025/49405/?folderId=749231

**Comment by pippinsplugins** [comment]
This is fixed now.
