### ISSUE TITLE
Use EDD_Payment to create payment records

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-free-downloads#148]
We should be leveraging EDD_Payment for creating the records during downloads.

**Comment by mintplugins** [comment]
Working for logged in and logged out users here. Payment records are created without any issues and free downloads work as normal.

**Comment by pippinsplugins** [comment]
@dannyb195 could you review this and give it some thorough testing to ensure it's all working.

**Comment by pippinsplugins** [comment]
It will need a merge conflict resolution.

**Comment by dannyb195** [comment]
PR at https://github.com/easydigitaldownloads/edd-free-downloads/pull/149

**Comment by cklosowski** [comment]
This was merged, going to close it out.
