### ISSUE TITLE
Add support for price_id parameter in [purchase_link] shortcode

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-free-downloads#153]
Free Downloads supports variable pricing with a free option but it does not support using the `[purchase_link]` shortcode and targeting that free price option using the `price_id` parameter. I believe it should.

Instead, it just acts like a regular Add to Cart button for a free product.

**Comment by pippinsplugins** [comment]
@ghost1227 I've been trying to test this but I cannot because of https://github.com/easydigitaldownloads/edd-free-downloads/issues/178

Can we please get #178 looked at for 2.1.8 as well?

**Comment by pippinsplugins** [comment]
@ghost1227 This is not working for me. When I attempt to download a file from `[purchase_link id="8" price_id="4"]`, I get this:

<img width="1225" alt="screen shot 2017-09-05 at 12 57 54 pm" src="https://user-images.githubusercontent.com/1034109/30075249-ea5f76b2-9239-11e7-9312-95deab219b3f.png">

Downloading from the main purchase button works fine though.

Product edit screen:
<img width="1067" alt="screen shot 2017-09-05 at 12 58 56 pm" src="https://user-images.githubusercontent.com/1034109/30075262-0327f228-923a-11e7-8146-58a9c6b8347d.png">

Frontend (top download button fails, bottom one works):
<img width="843" alt="screen shot 2017-09-05 at 12 59 19 pm" src="https://user-images.githubusercontent.com/1034109/30075275-0ef33c84-923a-11e7-8e0a-bd4b041ddc07.png">

**Comment by pippinsplugins** [comment]
Note: this was using a brand new, locally hosted file I just uploaded.

**Comment by ghost1227** [comment]
Note: The bug @pippinsplugins found only exists if a the shortcode is actually on a product page. The latest PR fixes price_id detection.

**Comment by SDavisMedia** [comment]
Having a hard time understand where this issue stands. But everything seems to be working for me on `issue/153`. It doesn't matter if there's one button on the page or two. It doesn't matter if it's in a page's content or in a download's content. The new `price_id` appears to be working in all of my tests.

If there's some scenario I'm missing, let me know. Otherwise, the new feature seems to be working just fine.

**Comment by ghost1227** [comment]
@SDavisMedia Nope, with the latest commits it should work everywhere. My original didn't work in one specific instance that Pippin found, but that's been resolved.

**Comment by SDavisMedia** [comment]
Oh okay. Well that's definitely a :+1: for me then. I couldn't break it.
