### ISSUE TITLE
Downloads fail when using Auto Download and Dropbox File Store

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-free-downloads#154]
When using the Auto Download feature and Dropbox File Store, file downloads don't work. The modal gets submitted but then nothing happens.

**Comment by pippinsplugins** [comment]
This likely affects Amazon S3 as well.

**Comment by ghost1227** [comment]
@pippinsplugins Amazon had its own handler already. DBFS support is in the 154 issue branch

**Comment by SDavisMedia** [comment]
Replicated on `master` and DFS 1.8.2 and confirmed fixed on FD `issue/154`. :+1:

**Comment by pippinsplugins** [comment]
Great, deploy at will!
