### ISSUE TITLE
Customer not being linked to purchase

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/edd-free-downloads#156]
When a customer creates an account from within the modal, the EDD payment is being created _without_ the customer attached. I believe this should attach the customer straight away, since they've just created an account.

![screen shot 2017-03-22 at 3 51 11 pm](https://cloud.githubusercontent.com/assets/52581/24180157/27d7fffa-0f18-11e7-8a51-2e337029aeb2.png)

I've tested https://github.com/easydigitaldownloads/edd-free-downloads/pull/149 but that didn't help.

**Comment by pippinsplugins** [comment]
Probably related to https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5579

**Comment by ghost1227** [comment]
@amdrew Can we confirm if this still exists after https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5579?

**Comment by pippinsplugins** [comment]
Appears to be resolved. None of our sites show the issue.

**Comment by amdrew** [comment]
👍 I can confirm this is now working for me
