### ISSUE TITLE
JS error when 'add-to-cart' is not a class that exists

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-free-downloads#157]
This is an integration issue with All Access - which replaces the normal Add To Cart button with a "Download" button. When it does, the 'edd-add-to-cart' class is removed from the button and replaced with a more relevant class from All Access. 

This doesn't actually break anything but it does throw an error in the JS console. The error is:

```
Cannot read property 'replace' of undefined
```

We'll just need to add a check to make sure that edd-add-to-cart is a class before we remove it here:

Line 12 of edd-free-downloads.js:
```
 classes = classes.replace('edd-add-to-cart', '');
```

**Comment by dannyb195** [comment]
PR at https://github.com/easydigitaldownloads/edd-free-downloads/pull/190

**Comment by mintplugins** [comment]
The fix in its current state didn't work because running `classes.length` also resulted in an undefined error. By checking if the `classes` variable has any value at all before using it, it solves the issue. I added a commit which does that to the PR. It changes `if ( classes.length )` to ` if ( classes ) `.

**Comment by mintplugins** [comment]
Actually, this was resolved already...I think we can just close this.

**Comment by mintplugins** [comment]
This issue is a duplicate of https://github.com/easydigitaldownloads/edd-free-downloads/issues/171

Closing and deleting branch
