### ISSUE TITLE
Add context to "Download Now" strings

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-free-downloads#16]
So we have a user who is okay with "Download Now" displaying on the purchase form submit button but he wants to change the submit button in the modal to "Send Download Link."

Unfortunately, each instance of this output is either going to use the `edd_free_downloads_button_label` option from the dashboard or, if left blank, its default, which has no context. So Say What? won't even work because there's no way to target one specific instance of the string. We just need a little `_x()` love.

**Comment by ghost1227** [comment]
Not necessary. Next version of FD gets rid of the redundancy in the plugin. Only one place to screw with now! Also, the modal/form will be MUCH more customizable in the next version (take a look at a few of the issues I opened yesterday).

**Comment by SDavisMedia** [comment]
Nice! So how is this part going to work specifically? One place to handle it all would be great. But if the output is in more than one place, we still either need context or multiple EDD (or customizer) options added.

**Comment by ghost1227** [comment]
Still working through it... Gimme time ;)

**Comment by SDavisMedia** [comment]
Haha you got it.

**Comment by ghost1227** [comment]
Added an explicit option for this for now
