### ISSUE TITLE
Issues if no file attached and "Bypass if Logged In" for Modal

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-free-downloads#161]
If you have the "Bypass If Logged In" option enabled to bypass the popup modal for logged in users and no file is attached, the user is not redirected to the purchase confirmation, nor is any file downloaded. The page simply refreshes with this appended to the URL:

```
?edd_action=free_downloads_process_download&download_id=25&price_ids&payment-id=58
```

This should still redirect the customer to the purchase confirmation screen (or their custom redirect) - even if no files are attached. 

The only scenario where this should act differently is if the "On-Complete Handler" is set to "Auto Download". There, likely an error screen should be displayed to say that "No File is Attached". This way, the site owner is directed to how to fix the issue without being confused and needing to contact support.

**Comment by mintplugins** [comment]
Customer Ticket:
https://secure.helpscout.net/conversation/377350834/60666/

**Comment by pippinsplugins** [comment]
While this is a bug for sure, is there a reason there is no file attached?

**Comment by mintplugins** [comment]
Not in this scenario no. However, I could see a situation where you are selling a service or All Access where you might not have one attached.

**Comment by pippinsplugins** [comment]
Let's resolve this by redirecting to the success page without a file download action when there are no download files.

**Comment by dannyb195** [comment]
https://github.com/easydigitaldownloads/edd-free-downloads/compare/release/2.2.0...issue/161?expand=1

**Comment by dannyb195** [comment]
found new bug that a new purchase record is not created for logged in users with the modal off as recorded in #196

**Comment by mintplugins** [comment]
@dannyb195 Looks good in my tests. 

I'm wondering if we could fix a somewhat related issue here as well. 

If you try to download a free product on android while logged in in this scenario (with a product attached or not), it redirects to have `&edd_action=free_downloads_process_download&download_id=8&price_ids=` appended to the URL. The problem is that there isn't a `?` in the URL so `&` shouldn't be used. 

You can test this by viewing the product like this:

- Make sure you are logged in
- Make sure popup modal is disabled
- View it using "device" mode in Google Chrome
- Try downloading the product


![free-downloads-modal-loggedin-mobile](https://user-images.githubusercontent.com/1638128/30936833-e72d13d0-a389-11e7-944e-d8bbac9aa4f9.jpg)

**Comment by mintplugins** [comment]
Nevermind I'm making this a separate issue.

**Comment by dannyb195** [comment]
closing PR #195 (this) due conversation with pippin to do two difference PRs for #161 and #195

**Comment by pippinsplugins** [comment]
Just one little issue I found with this: missing `exit;` after the redirect. I've added it.
