### ISSUE TITLE
Using exit in download-redirect.php prevents other scripts from loading.

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/edd-free-downloads#164]
Free downloads uses `exit` here:
https://github.com/easydigitaldownloads/edd-free-downloads/blob/master/templates/download-redirect.php#L135

I understand why this was initially done but this seriously messes with the HTML:

1. The page is now not valid. There's no closing body or html tag:

    <img width="1106" alt="screenshot 2017-06-21 15 37 35" src="https://user-images.githubusercontent.com/52581/27366073-edd3e66c-5697-11e7-97c9-2c90a3117b7a.png">

2. Because it exits early, some inline styles added to the `<head>` do not get rendered at all. The HTML exits after free downloads loads its own template, everything else is gone. I'd imagine this is the same for some scripts being loaded in the head, as well as footer. This causes an issue in Themedd, whereby the customizer styles do not override the default styling. I can move the inline styles higher, but then they are loaded before the stylesheet and do not take priority.

Instead of using exit, I'm sure we could instead use something like `template_include()`? to replace the template? Then we can keep all the HTML intact.
https://codex.wordpress.org/Plugin_API/Filter_Reference/template_include

**Comment by ghost1227** [comment]
This should be fixed with #165

**Comment by amdrew** [comment]
Neat! Though I'm not seeing any difference on the 165 issue branch.

**Comment by ghost1227** [comment]
Check https://github.com/easydigitaldownloads/edd-free-downloads/pull/169

**Comment by SDavisMedia** [comment]
@amdrew can you give this a test?

**Comment by amdrew** [comment]
@SDavisMedia It doesn't look like there have been any more commits since I last tested.

@ghost1227 #169 is the PR for the `issue/165` branch which I tested. I don't see any difference, I still see the `exit()` etc.

What should I be seeing? Does the mobile version now show a modal window instead of the template file with the `exit()`?

**Comment by pippinsplugins** [comment]
@ghost1227 ping

**Comment by ghost1227** [comment]
@amdrew It still exits, but now runs `wp_footer();` before bailing. In my tests, this fixed issues with footer scripts as long as they were being run correctly in the first place.

**Comment by amdrew** [comment]
@ghost1227 Sadly this isn't fixed.

As per my original comment https://github.com/easydigitaldownloads/edd-free-downloads/issues/164#issue-237406741 some inline styles that are loaded into the `<head>` are not loaded at all. 

Free downloads still exits right after its template is loaded. Calling `wp_footer()` won't fix this, since the styles are loaded into the `<head>`. 

Here's a simple function to illustrate, and to replicate the issue:

```php
function edd_free_downloads_issue_164() {
	?>
	Hello
	<?php
}
add_action( 'wp_head', 'edd_free_downloads_issue_164', 100 );
```

Load that and you'll see `Hello` on any page, it's loaded just fine:

<img width="693" alt="screenshot 2017-09-01 12 34 36" src="https://user-images.githubusercontent.com/52581/29950767-0085110c-8f12-11e7-8aeb-04068abbc4f2.png">

Now try purchasing a free download on a mobile device. The `Hello` does not exist in the HTML because Free Downloads' template file has already exited before it can be loaded.

<img width="361" alt="screenshot 2017-09-01 12 34 40" src="https://user-images.githubusercontent.com/52581/29950774-0b3609d0-8f12-11e7-95d2-a4c9bcba81b5.png">

**Comment by ghost1227** [comment]
@amdrew It seems to me that we can fix that by simply adding an additional call to wp_head at the beginning of the form much like how we added wp_footer... Right? If so, that's an easy fix.

**Comment by ghost1227** [comment]
Additionally, I dropped your function into my dev site, and got the following on mobile:

![img_0049 2](https://user-images.githubusercontent.com/36433/30005746-e4c9d684-90ae-11e7-9887-273827e82b2a.PNG)

**Comment by ghost1227** [comment]
Though I'm not sure that'd work either... @pippinsplugins suggestions?

**Comment by amdrew** [comment]
@ghost1227 Including `wp_head()` won't work since you're already loading `edd_free_downloads_display_redirect()` on `wp_head()`. It will create an infinite loop of forms.

From what I can see, the entire issue stems from the `download-redirect.php` template file being injected into the`<head>`, using the `wp_head()` action hook. 

If the form is the only thing that is being displayed on mobile (which I take it is the reason for the `exit()` in the first place) then the template file needs to be valid (and complete) HTML (As per point 1 in the original issue). Loading `wp_footer()` into the `<head>` doesn't really make sense to me and the HTML ends up worse off. 

I think my original suggestion of using the `template_include` filter is the solution for this issue. 

See this PR: https://github.com/easydigitaldownloads/edd-free-downloads/pull/177

The `download-redirect.php` template file is now a full HTML template and the form is the only thing loaded onto the page. 

Scripts that are loaded late (like in my earlier example) can now be loaded, and the HTML is 100% valid. It's just a simple HTML file with `wp_head()` and `wp_footer()` being called, and the form in the `<body>`. The template file can still be overridden from the theme's `edd_templates` folder.

I'm not 100% familiar with the codebase, can anyone see any issues with that?

**Comment by pippinsplugins** [comment]
@amdrew @ghost1227 this is working great for me, merging.
