### ISSUE TITLE
Direct downloads fail on Apple devices. 

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-free-downloads#165]
Because Apple does not allow direct downloading, if you have the "On-Complete Handler" set to "Auto Download", nothing happens. 

Perhaps we should add an option to have different On Complete Handlers depending on the type of device the user is on. 

On-Complete Handler for Desktop:
On-Complete Handler for Apple Mobile Devices:
On Complete Handler for non-Apple Mobile Devices:

**Comment by SDavisMedia** [comment]
I can't get this to detect that I am on an iPad. And auto-download actually works for me. So from my iPad, it's just respecting whatever the regular on-complete handler is set to.

Someone with an iPhone may want to test.

**Comment by mintplugins** [comment]
I just learned that iPads actually have support for file downloading in the latest iOS. Which version are you on @SDavisMedia?

**Comment by SDavisMedia** [comment]
10.3.2

**Comment by pippinsplugins** [comment]
@mintplugins does PR #165 resolve the issue for you?

**Comment by mintplugins** [comment]
@pippinsplugins @ghost1227 Yep this fixes both this and https://github.com/easydigitaldownloads/edd-free-downloads/issues/167 for me 👍
