### ISSUE TITLE
Direct Download does not work on mobile

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-free-downloads#167]
If you use the "Direct Download" option and the user is on a mobile device, if they click on the "No thanks I'll download it anyway", nothing happens. This is only an issue on mobile as it works on desktop. I tested using my android. 

<img width="954" alt="screen shot 2017-06-22 at 1 54 29 pm" src="https://user-images.githubusercontent.com/1638128/27448317-65a1712c-5752-11e7-9add-3c2671870e6c.png">

<img width="385" alt="screen shot 2017-06-22 at 1 57 13 pm" src="https://user-images.githubusercontent.com/1638128/27448425-bda254ea-5752-11e7-9bcc-829ab7fff665.png">

Again, if they click on the "No thanks I'll download it anyway", nothing happens. This is only an issue on mobile as it works on desktop. I tested using my android. 

On desktop the URL is:
`http://edd2.dev/free-downloads/downloads/product-b/?edd_action=free_downloads_process_download&download_id=25&price_ids=`

But on Mobile the URL is different and seems to link nowhere:
`http://edd2.dev/free-downloads/downloads/product-b/`

**Comment by pippinsplugins** [comment]
Related https://github.com/easydigitaldownloads/edd-free-downloads/issues/165 https://github.com/easydigitaldownloads/edd-free-downloads/issues/163

**Comment by ghost1227** [comment]
This should be fixed with #165

**Comment by mintplugins** [comment]
@ghost1227 Yep works now 👍
