### ISSUE TITLE
Fatal error when EDD isn't active

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/edd-free-downloads#168]
@ghost1227 

```
PHP Fatal error:  Uncaught Error: Call to undefined function edd_get_option() in /wp-content/plugins/edd-free-downloads/includes/scripts.php:23
```

To replicate, deactivate EDD when Free Downloads is still active.

**Comment by ghost1227** [comment]
I'm still not sure the best way to handle this, and it's a HUGE sticking point on pretty much every plugin out there. If you load anything, it is going to fail if EDD is disabled. Wrapping each reference in a check isn't a good solution, we've tried silently bailing if EDD isn't found, but have in the past determined that's not a good solution either... is there any sort of 'standard' at this point as to how this should be handled?? @pippinsplugins

**Comment by mindctrl** [comment]
Why do you load the plugin instance when EDD isn't active? https://github.com/easydigitaldownloads/edd-free-downloads/blob/2.1.7/edd-free-downloads.php#L169

Load the whole plugin when there's nothing for it to do seems very inefficient.

**Comment by pippinsplugins** [comment]
@ghost1227 this should just be simplified a lot. All you need to do is this:

1. Instantiate your class on `plugins_loaded`
2. Put all of your "start up" logic in a method called `init` (or similar)
3. In your `__construct()` method put this:

```php
if( ! class_exists( 'EDD' ) ) {
     add_action( 'admin_notices', 'edd_fd_edd_not_active_notice' );
     return; // Bail
}
$this->init(); // This only runs when EDD is active
```
Super simple and works perfectly. The activation class you use is way to convoluted and unreliable.

Simplicity is best.

**Comment by ghost1227** [comment]
Ok

**Comment by ghost1227** [comment]
@pippinsplugins This seems to work for me... No errors, just displays the notice.

**Comment by pippinsplugins** [comment]
Works great, thanks!
