### ISSUE TITLE
Feature request: bypass modal when user logged in

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-free-downloads#17]
Would be nice to bypass the modal when a user is logged in. [Requested here](https://secure.helpscout.net/conversation/98651233/11195/).

**Comment by mindctrl** [comment]
Related request - if someone has downloaded a product during a session, bypass modal on subsequent downloads by reading email info from a cookie or something.

**Comment by pippinsplugins** [comment]
Nice idea

**Comment by mindctrl** [comment]
[Another request](https://secure.helpscout.net/conversation/130613277/19032/).

**Comment by mindctrl** [comment]
[Another request](https://secure.helpscout.net/conversation/157879104/24662/?folderId=180504).

**Comment by pippinsplugins** [comment]
@ghost1227 please make sure issues are properly milestoned (hint this one is not).

**Comment by ghost1227** [comment]
@pippinsplugins Done. I've never done actual milestone tags on my plugins before... I'm working on actually using labels/milestones better lately... but it's a learning experience.
