### ISSUE TITLE
Conflicting plugin "Event Calendar WD"

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-free-downloads#170]
A customer has reported that the "[Event Calendar WD](https://wordpress.org/plugins/event-calendar-wd/)" plugin caused Free Downloads to not generate payments upon modal form submission.  

I just wanted to log this.

**Comment by ghost1227** [comment]
Can you tell me if it prevents anything else? IE, are downloads still triggered? Does it JUST block payments, or break entirely?

**Comment by dannyb195** [comment]
This has been confirmed on the stock 2017 theme

with Event Calendar WD active
<img width="572" alt="screen shot 2017-09-22 at 9 17 07 am" src="https://user-images.githubusercontent.com/247887/30748836-1b4288ba-9f77-11e7-9fbc-a18443cddd8a.png">


with Event Calendar WD *not* active
<img width="599" alt="screen shot 2017-09-22 at 9 18 22 am" src="https://user-images.githubusercontent.com/247887/30748871-35ada90a-9f77-11e7-9772-f4d8d036ec10.png">

No JS console errors are found. More research needed.

**Comment by dannyb195** [comment]
for some reason when both Event Calendar WD and EDD Free Downloads are both active EDD core function of edd_is_payment_complete() believes that the $payment->status is `future` rather than `publish`

**Comment by dannyb195** [comment]
this has been reported to Event Calendar WD at https://wordpress.org/support/topic/inadvertent-php-global-timezone-setting/
