### ISSUE TITLE
Larger files fail when hosted on Amazon S3 and Dropbox

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-free-downloads#173]
For a reason I'm not fully aware of, Free Download creates a local version of _all_ externally hosted files and then delivers the _local_ version to the customer instead of downloading directly from the external server.

Doing this 100% negates the purpose of using Amazon S3 and Dropbox for storing files.

We need to _not_ create local versions of externally hosted files and instead download them directly from the host.

**Comment by pippinsplugins** [comment]
This affects primarily large files because the clone process for large files consumes too much memory, resulting in server timeouts. Smaller files require less processing so they can be cloned successfully, though that still negates the purpose of external file hosting.

**Comment by pippinsplugins** [comment]
To test:

1. On `master`, upload a really large file (50-500mb) to Dropbox or S3
2. Set that file up as a Free Download
3. Attempt to download that file through Free Downloads using the Auto Download feature
4. The server should timeout.

Repeat test on `issue/173`.

**Comment by SDavisMedia** [comment]
Replicated on `master`. Working perfectly on `issue/173`. :+1:

**Comment by SDavisMedia** [comment]
I just tested the caching/bundling of local product files during auto download and everything is still working there to.
