### ISSUE TITLE
Trouble retrieving payment receipt when logged in as non-admin user

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-free-downloads#18]
I've seen 2 reports of this now and was just able to replicate it locally. If you're logged in as a non-admin user and make a free purchase, you'll get an error on the purchase confirmation screen that says "Thank you for your purchase! Sorry, trouble retrieving payment receipt.".

To replicate: log in as a subscriber user and make a free download purchase. I also replicated this on users with author and editor roles.

**Comment by pippinsplugins** [comment]
@mindctrl Are you only seeing this with Free Downloads or also with non-free downloads purchases on the same site?

**Comment by ghost1227** [comment]
Also, what other plugins are activated?

**Comment by pippinsplugins** [comment]
This is usually cased by page caching, either through a plugin or on the
server level.

**Comment by mindctrl** [comment]
@ghost1227 @pippinsplugins 
Only with purchases through Free Downloads. Non-free downloads work fine. 100% discounted through checkout work fine. No page or server caching locally. 

Happens on two different local installs I've tested (in addition to 2 customer reports). One of my local instals has only EDD and Free Downloads active.

**Comment by mindctrl** [comment]
Downloads > Purchase History shows the User as "guest", despite having been logged in while purchasing.

**Comment by pippinsplugins** [comment]
That's going to be why.

@ghost1227 can you double check that the user information is properly passed to the purchase record please?

**Comment by mindctrl** [comment]
Just a note for me to update [this customer](https://secure.helpscout.net/conversation/100075687/11592/).

**Comment by mindctrl** [comment]
Reopening this as it created a different problem, and it doesn't jive up with what EDD core does. We might need to look at it there, but I have a ticket about this change.

When logged out, if you make a purchase using an email address of a user account already on the system, the purchase gets attached to the user account, but the logged out user can't view the purchase receipt details. They get "Thank you for your purchase! Sorry, trouble retrieving payment receipt.".

This differs from core in that logged out purchases using the same email of an existing user get attached as 'guest', and are still visible on the confirmation screen.

We have the permissions checks [here](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/2.4.2/includes/shortcodes.php#L653), which is where it fails.

**Questions:**
are there any security concerns with:
1) attaching to the user like we now do with the changes we made here?
1a) if not, can/should we do this in core for logged out purchases using the same email as an existing user account?

2) modifying the permissions check in core to allow viewing when the user gets attached to an existing user from a logged out session and has an existing purchase session?

Other ideas I'm missing?

@pippinsplugins @cklosowski @ghost1227

**Comment by pippinsplugins** [comment]
Do you know why it fails? Which part of the security check is failing?

**Comment by mindctrl** [comment]
@pippinsplugins this: `$customer_id == 0 || $customer_id == '-1' `

that's because the payment user ID gets set [here](https://github.com/easydigitaldownloads/edd-free-downloads/blob/238761c5edefcd124466097cb0cceb7b6e720bf8/includes/functions.php#L66
) if there's an existing user with the email used on the purchase.

**Comment by mindctrl** [comment]
We fixed this in EDD core.
