### ISSUE TITLE
Cache files don't respect variable price options

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/edd-free-downloads#184]
RE: https://github.com/easydigitaldownloads/edd-free-downloads/issues/178#issuecomment-327579540

If you have a product with more than one free option, or change the free option in a variably priced product, FD doesn't account for differences when it creates cache files. Cache files are currently identified only by the download ID. We need to add a specification for WHICH price ID(s) are included in the cache file to allow for multiple variations.

**Comment by SDavisMedia** [comment]
Replicated the original issue on `master`. Confirmed that two separate free price options deliver different files, as they should, on `issue/184`. Also confirmed on that branch that any other changes to the files, like replacing one of the free files with a different file, causes a new zip to be cached. 

Looking good on my end. :+1:
