### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-free-downloads#186]
Currently, the same error message is used for almost all potential errors while attempting to download a free file. 

The error is this:
"An internal error has occurred, please try again or contact support."

When they contact support, the only way we can tell which error they are actually getting is by requesting FTP credentials and debugging the errors to narrow it down. 

If each error had a unique message, we could determine what is happening without requiring FTP credentials from the customer.

**Comment by dannyb195** [comment]
logic statements to address

- [ ] edd_is_email_banned
- [ ] download_id
- [ ] download
- [ ] download->post_type
- [ ] published download

**Comment by dannyb195** [comment]
https://github.com/easydigitaldownloads/edd-free-downloads/pull/193
