### ISSUE TITLE
Can't enable Required login

### ISSUE THREAD

**Issue by blackPantherOS** [easydigitaldownloads/edd-free-downloads#189]
Hi,

On Settings > Other > Orders 
I can't enable "Require Login  [ x ] Require that users be logged-in to purchase files" because still unchecked after I try save settings on page
also
I can't select in "Show Register / Login Form?" row the "Only Registration Form"  and " Login and Registration Form" because switch "None" after I try save settings on page

Do you have any suggestions?
Regards

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
