### ISSUE TITLE
Exclude Free Downloads in Reports

### ISSUE THREAD

**Issue by KienTrong** [easydigitaldownloads/edd-free-downloads#191]
Hi, how can I exclude Free Downloads purchases so the report can show actual purchase and Google Analytic Ecommerce show correct conversion rate for premium product?

Thanks.

**Comment by chriscct7** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
