### ISSUE TITLE
Logged in user when bypassing the purchase modal does not create a purchase record

### ISSUE THREAD

**Issue by dannyb195** [easydigitaldownloads/edd-free-downloads#196]
step to create

1. enable bypass if logged in
2. purchase a free product
3. no purchase record will be created

desired functionality is that a purchase record will be created thus # 3 above is a bug.

found while testing #161

**Comment by dannyb195** [comment]
this is a blocker of #161

**Comment by pippinsplugins** [comment]
At some point I recall having a discussion about this and the decision being made to intentionally not create purchase records here.

I think we should now go ahead and adjust it a bit:

1. If the logged-in user has _not_ purchased the item, create a purchase record
2. If the logged-in user _has_ purchased the item already, do not create a purchase record

**Comment by cklosowski** [comment]
I'm good with this decision. The fact that we weren't recording even a first transaction seems odd, but we deff need it for the acse of #161.

**Comment by dannyb195** [comment]
https://github.com/easydigitaldownloads/edd-free-downloads/pull/195

**Comment by dannyb195** [comment]
closing PR #195 (this) due conversation with pippin to do two difference PRs for #161 and #195

**Comment by cklosowski** [comment]
Found a small issue here...I'm not getting a gateway on the bypass when logged in:
![screen shot 2017-10-16 at 12 13 19 pm](https://user-images.githubusercontent.com/1390124/31630448-7b6d4854-b26b-11e7-8fd1-a0be5547accd.png)

**Comment by cklosowski** [comment]
@dannyb195 Can you look at the above and address that?

**Comment by cklosowski** [comment]
A few more things to test here, now that I re-opened it, all while logged in and bypass modal is enabled:
1) The gateway is properly set
2) The payment note is added stating it was delivered via free downloads
3) Test that you get the purchase confirmation for the following config:
a) Bypass Modal when logged in
b) Logged in
c) Download has files
d) Redirect to purchase confirmation is the on-complete handler.

**Comment by dannyb195** [comment]
https://github.com/easydigitaldownloads/edd-free-downloads/issues/196#issuecomment-337034672 is confirmed locally by me
