### ISSUE TITLE
Goes to checkout when more than one download files exists

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-free-downloads#2]
When a download has more than one file in the File Downloads box, you get directed to the checkout instead of getting the normal popup.

**Comment by mindctrl** [comment]
Another ticket for this here. https://easydigitaldownloads.com/support/topic/free-download-not-working/#post-514590

**Comment by mindctrl** [comment]
@ghost1227 https://easydigitaldownloads.com/support/topic/free-download/

**Comment by ghost1227** [comment]
Fixed with 630ea7f64187b724084cc7d55bc3db77520b152f
