### ISSUE TITLE
improve check for EDD

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-free-downloads#20]
Need to check for EDD before getting here or fatal error: https://github.com/easydigitaldownloads/edd-free-downloads/blob/master/includes/scripts.php#L21

**Comment by ghost1227** [comment]
It does check... https://github.com/easydigitaldownloads/edd-free-downloads/blob/master/edd-free-downloads.php#L469

The only guaranteed way to always prevent fatal errors is to wrap EVERY edd_get_option call in a check...

**Comment by pippinsplugins** [comment]
@SDavisMedia was that perhaps caused by an old version of EDD?

**Comment by SDavisMedia** [comment]
2.4.1 but that shouldn't matter in this case. Correct me if I'm wrong, but deactivating EDD should not cause a fatal error in any extension. It came from needing to temporarily deactivate EDD (I knew the risks before I did it, but that's how I find these errors). I had maybe 10 extensions activated at the time and Free Downloads is the only one that had a fatal error.

**Comment by pippinsplugins** [comment]
It shouldn't trigger a fatal error.

Thing is . . . Dan's code looks correct. It shouldn't be loading . . .

**Comment by chriscct7** [comment]
Um, read the code again:
```
 if( ! class_exists( 'Easy_Digital_Downloads' ) ) {
        if( ! class_exists( 'S214_EDD_Activation' ) ) {
            require_once 'includes/class.s214-edd-activation.php';
        }
        $activation = new S214_EDD_Activation( plugin_dir_path( __FILE__ ), basename( __FILE__ ) );
        $activation = $activation->run();
        return EDD_Free_Downloads::instance();
    } else {
        return EDD_Free_Downloads::instance();
    }
```

If EDD doesn't exist, still run the plugin anyways. 

It totally doesn't work. Installed EDD, activated it. Installed this, activated it. Deactivated EDD. World is on fire.

**Comment by pippinsplugins** [comment]
oh, what the fuclk.

@ghost1227

**Comment by chriscct7** [comment]
Should be:
```
 if( class_exists( 'Easy_Digital_Downloads' ) ) {
        if( ! class_exists( 'S214_EDD_Activation' ) ) {
            require_once 'includes/class.s214-edd-activation.php';
        }
        $activation = new S214_EDD_Activation( plugin_dir_path( __FILE__ ), basename( __FILE__ ) );
        $activation = $activation->run();
        return EDD_Free_Downloads::instance();
    } else {
        // return since EDD isn't active
    }
```

**Comment by mindctrl** [comment]
This is also in the boilerplate here, and probably a number of extensions built from it.  https://github.com/easydigitaldownloads/EDD-Extension-Boilerplate/blob/master/plugin-name/plugin-name.php#L232

**Comment by pippinsplugins** [comment]
@ghost1227 please get an update pushed out for the boilerplate today.
