### ISSUE TITLE
File downloads from Amazon S3 / Dropbox fail when Auto Download is enabled

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-free-downloads#204]
If the `On-Complete Handler` is set to `Auto Download` and Amazon S3 is being used, download files come down at 0 bytes.

**Comment by pippinsplugins** [comment]
Ticket: https://secure.helpscout.net/conversation/443108809/67867/

**Comment by pippinsplugins** [comment]
This also affects files on Dropbox.

**Comment by pippinsplugins** [comment]
This is actually working fine for me with S3.

To replicate on `master`:

1. Create free product with a file stored on Dropbox through [Dropbox File Store](github.com/easydigitaldownloads/edd-dropbox-file-store)
2. Enable `Auto Download` for the `On-Complete Handler` in FD settings
3. Download the file and you will receive a corrupted file
4. Repeat tests on `issue/204`

**Comment by sunnyratilal** [comment]
Bug replicated on `master` and fix confirmed on `issue/204`

**Comment by pippinsplugins** [comment]
@cklosowski moved this to 2.2 instead of 2.1.9.

**Comment by pippinsplugins** [comment]
This is still happening unfortunately. Investigating.

**Comment by pippinsplugins** [comment]
Looks like it's failing for S3 because the file is being pulled from cache even though the caching is disabled:

```
$download_url = array_values( $download_files );
$download_url = $download_url[0]['file'];

$hosted = edd_free_downloads_get_host( $download_url );
if ( 'local' !== $hosted ) {
	$download_url = edd_free_downloads_fetch_remote_file( $download_url, $hosted );
	$download_url = str_replace( WP_CONTENT_DIR, WP_CONTENT_URL, $download_url );
}
```

The file requested is from S3 from the `$download_url` came out as `https://site.com/wp-content/uploads/edd-free-downloads-cache/SAWTB.zip1`.

**Comment by pippinsplugins** [comment]
Actually this was failing because we were looking for ` $GLOBALS['edd_s3']`, which is no longer set in EDD S3 2.3+.

**Comment by pippinsplugins** [comment]
Deploying beta-3.
