### ISSUE TITLE
Settings header should match our current standards

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-free-downloads#21]
Current:
![image](https://cloud.githubusercontent.com/assets/1254870/8887815/e2ca9e30-3260-11e5-8ec9-8f9a3db0aeae.png)

New:
![image](https://cloud.githubusercontent.com/assets/1254870/8887818/eda64764-3260-11e5-8f56-756f1d8d899e.png)

**Comment by pippinsplugins** [comment]
:+1:
