### ISSUE TITLE
No log entry created when downloading files from modal

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-free-downloads#214]
Downloads -> Reports -> Logs ... filtered by `File Downloads`

When using the Free Downloads modal, no log entry is created for downloaded product files.

**Comment by dannyb195** [comment]
Clearing out all FD settings (thus ending up on the confirmation page) does create a log me for in both master (96c3203) and release/2.2.0 (c6ae204).

This said, if the `on-complete handler` is set to `auto download` a log _is not_ created. I am considering this the focus of this issue for now.

**Comment by dannyb195** [comment]
PR at https://github.com/easydigitaldownloads/edd-free-downloads/pull/218/files

**Comment by cklosowski** [comment]
Since downloading from the purchase confirmation uses a normal download link generation...it's not expected that Free Downloads handle that link, the only time it should be free Download's responsibility to make a long entry is when a file is auto-downloaded.

**Comment by cklosowski** [comment]
@easydigitaldownloads/core-devs this is ready for testing.
