### ISSUE TITLE
Using any language except English results in custom "Download Now" option not being used

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-free-downloads#222]
If you switch your translation to any language except English, it will use the translated value for the "Download Now" button's text instead of what you've filled out in the settings for Free Downloads. 

I believe this bug came into existence here:
https://github.com/easydigitaldownloads/edd-free-downloads/issues/98

I have narrowed the break down to happening here:
https://github.com/easydigitaldownloads/edd-free-downloads/blob/master/includes/filters.php#L98

**Comment by cklosowski** [comment]
@mintplugins Am I missing something? I set my site to German (Deutsch) and this is my

Settings:
![screen shot 2017-11-16 at 4 44 58 pm](https://user-images.githubusercontent.com/1390124/32922048-956a711a-caed-11e7-81d2-c590c68afe06.png)
Modal and button:
![screen shot 2017-11-16 at 4 45 03 pm](https://user-images.githubusercontent.com/1390124/32922050-9a606562-caed-11e7-80dc-9b31f6d5d9ff.png)

**Comment by mintplugins** [comment]
Hmm. Do you have french?

**Comment by mintplugins** [comment]
The text itself does need to actually be in a different language I think.

**Comment by cklosowski** [comment]
@mintplugins and I discussed this over Zoom. I have a good idea how to replicate now.

**Comment by cklosowski** [comment]
@mintplugins this is ready to test!

**Comment by mintplugins** [comment]
Looks good!
