### ISSUE TITLE
Set form float to none to defend against aggressive themes

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-free-downloads#224]
<img width="1553" alt="screen shot 2017-11-13 at 10 19 22 am" src="https://user-images.githubusercontent.com/1034109/32736051-25e11094-c85c-11e7-8765-c98e788abaf0.png">

The above screenshot shows what happens to the download modal when a theme is overly aggressive and sets a float on the `form` element.

Let's add `float:none` to our form and form fields to defend against this.

**Comment by cklosowski** [comment]
To replicate:

Setup a child theme of vendd and add the following style to the `styles.css` file:
```
    form {
        clear: both;
        float: left;
        width: 100%;
    }
```
