### ISSUE TITLE
Modal unable to be re-opened

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-free-downloads#229]
If you open the new modal from 2.2.0, close it, and then try to re-open it, nothing happens. 

Additionally, it gives an ajax error on the first load in the console. This may be the cause of further opening issues:

<img width="1440" alt="screen shot 2017-12-04 at 10 15 34 am" src="https://user-images.githubusercontent.com/1638128/33559877-302337f4-d8dc-11e7-9792-a105263fecc6.png">

**Comment by samikeijonen** [comment]
I confirm that I noticed the same.

**Comment by mintplugins** [comment]
I've fixed this by removing the `edd-add-to-cart` class on the Free Downloads button. Everything works correctly now in my tests.

The only drawback to this is that some theme authors may have used that class to style the `Add To Cart` button, and those styles won't automatically apply to the Free Downloads button any more. 

Those theme authors will want to style the `edd-submit` class instead.

**Comment by mintplugins** [comment]
I have tested this in both single, variable, and multi-price option mode. All are working well.

**Comment by pippinsplugins** [comment]
@mintplugins could you test in all of our main EDD themes to confirm they all style it properly?

**Comment by mintplugins** [comment]
@pippinsplugins I just tested in TwentySeventeen, Themedd, Vendd, and Marketify. All style it correctly.

**Comment by SDavisMedia** [comment]
Tested here as well. All good on my end. :+1:

**Comment by mintplugins** [comment]
Merged!
