### ISSUE TITLE
No redirect after form submission in Firefox

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-free-downloads#230]
If you have the "On Complete Handler" set to show "Purchase Confirmation", in Chrome it properly directs to the Purchase Confirmation despite the error being present. 

But in Firefox it simply closes the modal and nothing else happens. 

Possibly related:
https://github.com/easydigitaldownloads/edd-free-downloads/issues/229

**Comment by mintplugins** [comment]
The problem was that the closing of the modal after submission meant Firefox didn't have the form on the screen anymore, and thus did not submit it. 

It seems to be some sort of strange timing issue in Firefox in that the form is submitted after the modal was closed, even though the code is in the opposite order. 

Leaving the modal open allows it to submit properly.

**Comment by pippinsplugins** [comment]
This looks good to me.

**Comment by mintplugins** [comment]
Merged
