### ISSUE TITLE
Direct Download does not work 

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-free-downloads#234]
If you enable the "Direct Download" option and put the [edd_free_download] shortcode onto a page, clicking `No thanks I'll download it anyway` will change the URL, but nothing will happen. 

Example shortcode usage:
`[edd_free_download download_id="155"]Test[/edd_free_download]`

The URL becomes this, but again, nothing actually downloads:
https://edd2.dev/free-downloads/free-downlods-shortcode/#edd-free-download-modal?edd_action=free_downloads_process_download&download_id=155&price_ids=

**Comment by mintplugins** [comment]
The issue seems to be the direct download link in general - not just when using the shortcode

**Comment by mintplugins** [comment]
There's some inconsistent behaviour here. 

The problem is caused by the fact that `#edd-free-download-modal` is added to the URL when the modal opens. It then tries to add URL variables to the url after the hash - which browsers don't understand. Notice the question mark after the `#` in this URL:

`https://edd2.dev/free-downloads/free-downlods-shortcode/#edd-free-download-modal?edd_action=free_downloads_process_download&download_id=155&price_ids=`

This is caused here:
https://github.com/easydigitaldownloads/edd-free-downloads/blob/821a86a565ebd0a36176a4e0b7ed8ed75445578b/assets/js/edd-free-downloads.js#L419

However, there is a related problem. This bug only happens for single products, when it really should be a bug for both variably-priced and single-priced products. Currently `#edd-free-download-modal` is only added to the URL if the modal is opened for a single-priced product. It does not get appended to the URL if the product is variably-priced. So there is an inconsistency in behaviour here that also needs to be addressed first. 

Once I address that, I'll take a look at how we can fix the issue with the `?` being added after the `#`.

**Comment by mintplugins** [comment]
This is ready for testing

**Comment by pippinsplugins** [comment]
Replicated bug on master and confirmed fix on `issue/234`. Merging.
