### ISSUE TITLE
Add 'loading' state between overlay and modal form loading.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-free-downloads#236]
On a slow site, the dark overlay comes in, but then there is a slight delay before the modal form shows. There should be a state in between bringing the overlay into view and the form loading that is a 'loading' state. A spinner or something.

**Comment by SDavisMedia** [comment]
Working well! I moved the CSS to the CSS file and added a little more to it. Reason being, @cklosowski added this feature while using Vendd and _something_ in Vendd caused the icon to be centered on the page already. What a coincidence, but won't be centered in the majority of themes.

My update to the PR adds CSS that centers the icon properly regardless of theme.

![slack-imgs-1](https://user-images.githubusercontent.com/2359131/38437769-5e64dbd8-398d-11e8-9d82-2405e0ddf9ac.png)
![slack-imgs](https://user-images.githubusercontent.com/2359131/38437770-5e7e6c2e-398d-11e8-80de-d5e18ea93d19.png)

All good here. :+1:
