### ISSUE TITLE
Mobile is error

### ISSUE THREAD

**Issue by tongdaitructuyen** [easydigitaldownloads/edd-free-downloads#248]
I check required verified Email, Desktop working, but mobile do not working, please view image attach.
Thank
![9023054693031279007](https://user-images.githubusercontent.com/5338282/34962782-c8f542f8-fa77-11e7-801f-c849ddf147e7.png)

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
