### ISSUE TITLE
No modal opens on Mobile for Variable product

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-free-downloads#249]
If you are on mobile and click to download a variable (non single) product, the modal does not open. 

It works on single and redirects the user to a URL like this:
`https://eddtests.com/downloads/test/?edd-free-download=true&download_id=378`

But if the product has variable pricing, the modal does not work, again, only on mobile. It gives this:
`https://eddtests.mintplugins.com/downloads/free-with-variable-prices/?edd-free-download=true`

Which has no affect on the page.

**Comment by cklosowski** [comment]
Looks like the Download ID isn't getting appended, as well as the price_id. Will get this fixed up.

**Comment by cklosowski** [comment]
@mintplugins @SDavisMedia this is ready for a look over and testing.

**Comment by SDavisMedia** [comment]
Hmmm I'm not getting a difference in behavior when I test on Chrome and Firefox (Android). No modal opens and the URL structure is the same that Phil mentioned. Caches are cleared.

**Comment by SDavisMedia** [comment]
Scratch dat... my mistake. All good here. It's working perfectly for me now and single price is still working as it should. :+1:

**Comment by cklosowski** [comment]
@mintplugins as the original reporter, you mind looking over this for a quick second, make sure it's meeting all your original issues?

**Comment by mintplugins** [comment]
@SDavisMedia I'm having the same issue you originally reported here. What did you have to do to get it working? I cleared caches

**Comment by SDavisMedia** [comment]
@mintplugins I was testing on my live test site where I didn't have script debug enabled. Not my normal testing site. So I just didn't have the updated resources. Complete false alarm.

**Comment by mintplugins** [comment]
Hmm. I'm loading the non-minified js and double checked that it's loading the newly-changed code. But I'm still having the same problem. 

Steps I'm taking:
1. Incognito Window, logged-out, viewing free download with variable prices
2. Attempt to download the free variable price
3. URL changes to `https://edd2.dev/free-downloads/downloads/product-f/?edd-free-download=true` and nothing else changes on the page or happens.

**Comment by cklosowski** [comment]
@mintplugins Doing the same thing, working fine here:
![screen shot 2018-04-18 at 4 30 50 pm](https://user-images.githubusercontent.com/1390124/38963273-e93e3550-4325-11e8-9b5b-2d9ca8775ec0.png)

**Comment by cklosowski** [comment]
@mintplugins what happens if you reorder your variable pricing? and put the free one at the bottom, not as the default price?

**Comment by cklosowski** [comment]
could be that the initial load isn't appending the proper values, but clicking on one of the inputs is going through and making the necessary changes.
