### ISSUE TITLE
Notice when file URL is external and attachment_id doesn't exist

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-free-downloads#25]
When the download being delivered via Free Downloads is an externally pasted URL (and therefore an attachment_id input isn't entered), the checkout process returns a notice:
`Notice: Undefined index: attachment_id in /Users/cklosowski/WordPress/src/wp-content/plugins/edd-free-downloads/includes/functions.php on line 91`
![screen shot 2015-09-11 at 10 42 10 am](https://cloud.githubusercontent.com/assets/1390124/9821834/cb1b379a-5871-11e5-972b-fd5faa4e2765.png)

**Comment by ghost1227** [comment]
@cklosowski My fault, it actually shouldn't even be storing attachment_id... It should be storing download_id.
