### ISSUE TITLE
Wrong newsletter lists used in MailChimp

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-free-downloads#254]
If opt-in is enabled in the FD settings, the MailChimp integration assumes that we should be using the default list in MailChimp, which is wrong.

We need to _always_ use the list that is selected on the product and then, if no list is selected, fallback to the default list.

**Comment by pippinsplugins** [comment]
Turns out this affects all email integration.

**Comment by pippinsplugins** [comment]
I'm going to fix this with MailChimp only. At the moment that's the only one causing problems.

**Comment by pippinsplugins** [comment]
This depends on https://github.com/easydigitaldownloads/edd-mail-chimp/issues/58 being fixed.

**Comment by pippinsplugins** [comment]
@mintplugins could you please give this a test? Note, use the latest `master` version of EDD MailChimp.

**Comment by mintplugins** [comment]
Just confirming the problem and solution:

Previously, the product-specific lists were being ignored for Free Downloads, and now the user should be subscribed to both the product-specific lists and the default list?

**Comment by mintplugins** [comment]
@pippinsplugins

**Comment by mintplugins** [comment]
I am getting this error when doing a free download on `issue/254`:

```

( ! ) Fatal error: Uncaught Error: Access to undeclared static property: EDD_MailChimp::$checkout in /app/public/wp-content/plugins/edd-free-downloads/includes/actions.php on line 55
--



1 | 0.0000 | 367408 | {main}( ) | .../index.php:0
2 | 0.0004 | 367696 | require( '/app/public/wp-blog-header.php' ) | .../index.php:17
3 | 0.0007 | 368048 | require_once( '/app/public/wp-load.php' ) | .../wp-blog-header.php:13
4 | 0.0010 | 368824 | require_once( '/app/public/wp-config.php' ) | .../wp-load.php:37
5 | 0.0012 | 373096 | require_once( '/app/public/wp-settings.php' ) | .../wp-config.php:97
6 | 0.5960 | 10284136 | do_action( ) | .../wp-settings.php:450
7 | 0.5960 | 10284512 | WP_Hook->do_action( ) | .../plugin.php:453
8 | 0.5960 | 10284512 | WP_Hook->apply_filters( ) | .../class-wp-hook.php:310
9 | 0.6293 | 10637616 | edd_post_actions( ) | .../class-wp-hook.php:286
10 | 0.6293 | 10637720 | do_action( ) | .../actions.php:42
11 | 0.6293 | 10638096 | WP_Hook->do_action( ) | .../plugin.php:453
12 | 0.6293 | 10638096 | WP_Hook->apply_filters( ) | .../class-wp-hook.php:310
13 | 0.6293 | 10639224 | edd_free_download_process( ) | .../class-wp-hook.php:286
14 | 4.7618 | 10990168 | EDD_Payment->save( ) | .../download-actions.php:213
15 | 4.7624 | 10995008 | EDD_Payment->update_status( ) | .../class-edd-payment.php:859
16 | 4.7876 | 11000984 | do_action( ) | .../class-edd-payment.php:1745
17 | 4.7876 | 11001360 | WP_Hook->do_action( ) | .../plugin.php:453
18 | 4.7876 | 11001360 | WP_Hook->apply_filters( ) | .../class-wp-hook.php:310
19 | 4.7876 | 11002488 | edd_free_downloads_remove_optin( ) | .../class-wp-hook.php:288


```

The error is not happening on Free Downloads `master`

**Comment by mintplugins** [comment]
Opps - I wasn't on MC master. It is working there...confirming...

**Comment by mintplugins** [comment]
Customer was successfully added to both the default list and the product-specific lists, including product-specific interest groups.

**Comment by pippinsplugins** [comment]
@mintplugins is the default list assigned to the product too? We don't want to assign to the default list through FD. At least I don't think we do.

**Comment by mintplugins** [comment]
I believe we do because it would follow the way a normal purchase works.

**Comment by pippinsplugins** [comment]
FD intentionally unhooks the default subscribe actions so that's not supposed to be happening. I'll have to double check to see if it's acting like I intended.

**Comment by pippinsplugins** [comment]
Ok I think this is right after all. Merging and releasing.
