### ISSUE TITLE
On-Complete Handler "Auto Download" directing to purchase confirmation

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-free-downloads#258]
I have the On-Complete Handler set to "Auto Download". Whether logged in or out, I am getting the purchase confirmation page instead of it auto downloading and remaining on the same page. 

Here are my settings for anyone that wishes to attempt a replication:
<img width="1054" alt="screen shot 2018-03-16 at 10 38 00 am" src="https://user-images.githubusercontent.com/1638128/37526580-2478d4ca-2906-11e8-9913-9833e066f375.png">
<img width="1101" alt="screen shot 2018-03-16 at 10 38 38 am" src="https://user-images.githubusercontent.com/1638128/37526611-36962144-2906-11e8-9e0a-f082399f22d7.png">
<img width="1054" alt="screen shot 2018-03-16 at 10 38 55 am" src="https://user-images.githubusercontent.com/1638128/37526622-3e427690-2906-11e8-8baf-0306d783e36a.png">

**Comment by SDavisMedia** [comment]
@mintplugins I can't seem to replicate. What's your EDD version and server environment?

**Comment by mintplugins** [comment]
hmm maybe it's a weird local thing:

### Begin System Info ###

-- Site Info

Site URL:                 https://edd2.dev/free-downloads
Home URL:                 http://edd2.dev/free-downloads
Multisite:                Yes

-- Hosting Provider

Host:                     DBH: localhost, SRV: edd2.dev

-- User Browser

Platform:                 Apple 
Browser Name:             Chrome  
Browser Version:          64.0.3282.186 
User Agent String:        Mozilla/5.0 (Macintosh; Intel Ma 
			  c OS X 10_11_6) AppleWebKit/537.
                          36 (KHTML, like Gecko) Chrome/64
                          .0.3282.186 Safari/537.36
                          
-- WordPress Configuration

Version:                  4.9.4
Language:                 en_CA
Permalink Structure:      /%postname%/
Active Theme:             Vendd 1.1.10
Show On Front:            posts
ABSPATH:                  /app/public/
Remote Post:              wp_remote_post() works
Table Prefix:             Length: 5   Status: Acceptable
WP_DEBUG:                 Enabled
Memory Limit:             64M
Registered Post Stati:    publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, abandoned, processing, active, inactive

-- EDD Configuration

Version:                  2.8.10
Upgraded From:            None
Test Mode:                Disabled
AJAX:                     Enabled
Guest Checkout:           Enabled
Symlinks:                 Disabled
Download Method:          Redirect
Currency Code:            USD
Currency Position:        before
Decimal Separator:        .
Thousands Separator:      ,
Upgrades Completed:       upgrade_payment_taxes,upgrade_customer_payments_association,upgrade_user_api_keys,remove_refunded_sale_logs,upgrade_mailchimp_api3,upgrade_mailchimp_api3_default_list
Download Link Expiration: 24 hour(s)

-- EDD Page Configuration

Checkout:                 Valid
Checkout Page:            http://edd2.dev/free-downloads/checkout/
Success Page:             http://edd2.dev/free-downloads/checkout/purchase-confirmation/
Failure Page:             http://edd2.dev/free-downloads/checkout/transaction-failed/
Downloads Slug:           /downloads

-- EDD Gateway Configuration

Enabled Gateways:         Test Payment
Default Gateway:          Test Payment

-- EDD Tax Configuration

Taxes:                    Disabled
Tax Rate:                 0
Display On Checkout:      Not Displayed
Prices Include Tax:       No

-- WordPress Active Plugins

Easy Digital Downloads - Free Downloads: 2.2.8
Easy Digital Downloads - MailChimp: 3.0.3 (needs update - 3.0.4)
Ninja Forms: 3.2.9 (needs update - 3.2.16)

-- WordPress Inactive Plugins

Aelia Foundation Classes for Easy Digital Downloads: 1.6.5.160513
AffiliateWP: 1.9.3.1
Akismet Anti-Spam: 4.0.2 (needs update - 4.0.3)
APC Object Cache: 2.0.6
Billing Address Email Tag - Actual Country Name: 
Debug Bar: 0.9
Debug Bar Console: 0.3
Disable All WordPress Updates: 1.6.2 (needs update - 1.6.3)
Do Function Shortcode: 1.0.0
Duplicate Page: 2.4 (needs update - 2.5)
Easy Digital Downloads: 2.8.10 (needs update - 2.9)
Easy Digital Downloads - 2Checkout Gateway: 1.3.12
Easy Digital Downloads - Add to Cart Popup: 1.1.2
Easy Digital Downloads - Advanced Reports: 1.0.1
Easy Digital Downloads - Advanced Sequential Order Numbers: 1.0.6
Easy Digital Downloads - Aelia Currency Switcher: 1.4.5.160629
Easy Digital Downloads - All Access: 1.0.9
Easy Digital Downloads - Amazon S3: 2.3.8
Easy Digital Downloads - Authorize.net Gateway: 1.1.1
Easy Digital Downloads - Auto Register: 1.3.10
Easy Digital Downloads - AWeber: 2.0.6
Easy Digital Downloads - Bitcoin Currency: 1.0.0
Easy Digital Downloads - BitPay Gateway: 2.1.2
Easy Digital Downloads - Bookings: 2.2.4
Easy Digital Downloads - Braintree: 1.1.4
Easy Digital Downloads - Campaign Tracker: 1.0.0
Easy Digital Downloads - Checkout Fields Manager: 2.1.3
Easy Digital Downloads - Checkout Message: 1.0.7
Easy Digital Downloads - Check Payment Gateway: 1.3.4
Easy Digital Downloads - ClickBank Gateway: 1.3.1
Easy Digital Downloads - Coinbase: 1.0.5
Easy Digital Downloads - Commissions: 3.4.6
Easy Digital Downloads - Conditional Emails: 1.1.0
Easy Digital Downloads - Content Restriction: 2.2.5
Easy Digital Downloads - ConvertKit: 1.0.2
Easy Digital Downloads - Cross-sell & Upsell: 1.1.7
Easy Digital Downloads - Currency Converter: 1.2.0
Easy Digital Downloads - Custom Deliverables: 1.0.0
Easy Digital Downloads - Custom Emails for Custom Deliverables: 1.0.0
Easy Digital Downloads - Custom IPN URL for Paypal Standard: 
Easy Digital Downloads - Custom prices: 1.5.4
Easy Digital Downloads - Developer Tools: 1.0
Easy Digital Downloads - Discounts Pro: 1.4.8
Easy Digital Downloads - Donations: 1.0.0
Easy Digital Downloads - Download Image Watermark: 1.1.7
Easy Digital Downloads - Downloads As Services: 1.0.6
Easy Digital Downloads - Dropbox File Store: 2.0.2
Easy Digital Downloads - Dropbox Sync: 1.0.3
Easy Digital Downloads - Email Templates: 1.0.5
Easy Digital Downloads - Featured Downloads: 1.0.3
Easy Digital Downloads - Fraud Monitor: 1.0.8
Easy Digital Downloads - Frontend Submissions: 2.5.9
Easy Digital Downloads - Gateway Fees: 1.5.2
Easy Digital Downloads - GetResponse: 2.1.2
Easy Digital Downloads - Git Update Downloads: 1.0.5
Easy Digital Downloads - Gravity Forms Checkout: 1.4.2
Easy Digital Downloads - Hide Download: 1.2.8
Easy Digital Downloads - Invoices: 1.1.2
Easy Digital Downloads - JVZoo: 1.4.2
Easy Digital Downloads - Keep Add To Cart: 1.0.0.3
Easy Digital Downloads - MailPoet (formerly Wysija): 1.4
Easy Digital Downloads - Manual Purchases: 2.0.4
Easy Digital Downloads - Message: 1.1
Easy Digital Downloads - Netbilling: 2.5.0
Easy Digital Downloads - PagSeguro Payment Gateway: 1.4.4
Easy Digital Downloads - Password Meter: 1.2.1
Easy Digital Downloads - payment_id email tag.: 1.0
Easy Digital Downloads - PayPal Adaptive Payments: 1.3.3
Easy Digital Downloads - PayPal Payments Advanced: 1.1.1
Easy Digital Downloads - PayPal Website Payments Pro and PayPal Express Gateway: 1.4.4
Easy Digital Downloads - PayU India Payment Gateway: 1.0.6
Easy Digital Downloads - Payza Payment Gateway: 1.0.5
Easy Digital Downloads - PDF Invoices: 2.2.21
Easy Digital Downloads - PDF Stamper: 3.2.1
Easy Digital Downloads - Per Product Emails: 1.1.4
Easy Digital Downloads - Points and Rewards: 1.4.4
Easy Digital Downloads - Pricing Tables: 1.0
Easy Digital Downloads - Product Badges: 1.0.0
Easy Digital Downloads - Product Feeds: 1.3
Easy Digital Downloads - Product Updates: 1.3
Easy Digital Downloads - Purchase Limit: 1.2.19
Easy Digital Downloads - Recommended Products: 1.2.8
Easy Digital Downloads - Recurring Payments: 2.7.20
Easy Digital Downloads - Reviews: 2.1.6
Easy Digital Downloads - Sales Recovery: 1.3.5RC1
Easy Digital Downloads - Simple Shipping: 2.3.2
Easy Digital Downloads - Social Discounts: 2.1
Easy Digital Downloads - Social Links: 1.2.2
Easy Digital Downloads - SofortBanking: 1.0
Easy Digital Downloads - Software Licensing: 3.5.23
Easy Digital Downloads - Software Licensing - Renew All: 1.0.2
Easy Digital Downloads - Stripe Payment Gateway: 2.6.13
Easy Digital Downloads - Upload File: 2.1.2
Easy Digital Downloads - Variable Pricing Switcher: 1.0.5
Easy Digital Downloads - Volume Discounts: 1.3.1
Easy Digital Downloads - Wallet: 1.1.4
Easy Digital Downloads - Widgets Pack: 1.2.6
Easy Digital Downloads - Wish Lists: 1.1.4
Easy Digital Downloads - Xero: 1.2.12
Easy Digital Downloads - Zapier: 1.3.5
Easy Digital Downloads2 - CSV Manager: 1.2.8
Easy Theme and Plugin Upgrades: 2.0.0
EDD FES - Display Vendor-Submitted data as Restricted Content.: 1.0
EDD Sale Price: 1.0.4
EDD User Switching: 1.0
EDD Variable Pricing Descriptions: 1.0.3
EDD {payment_id} Email Tag - Pluginception: 1.0.0
Envato Integration - Easy Digital Downloads: 1.0.1
FacetWP: 3.1.0
Featured Video Plus: 2.3.3
FES Codes: 
Gravity Forms: 2.0.2
Gutenberg: 2.0.0 (needs update - 2.4.0)
Hello Dolly: 1.6
License Keys UL - Email Tag for Software Licensing.: 1.0.0
MailPoet 2: 2.8.1 (needs update - 2.8.2)
miniOrange 2 Factor Authentication: 4.5.7 (needs update - 4.5.8)
MP Core: 1.0.4.7 (needs update - 1.0.5.0)
MP Menu: 1.0.0.5
MP Player Core: beta1.0.0.0
MP Stacks: 1.0.6.0 (needs update - 1.0.6.3)
PDF Invoice For Pendings: 
Phil's Custom Taxonomy: 
PHP Compatibility Checker: 1.4.4 (needs update - 1.4.5)
Pluginception: 1.3
Plugin Toggle: 1.3.1
reCAPTCHA for Easy Digital Downloads: 1.0.0
Restrict Content Pro: 2.8.5
Restrict Content Pro - EDD Member Downloads: 1.0.3
Say What?: 1.9.1
SendGrid: 1.11.7 (needs update - 1.11.8)
Show Site Number: 1.0.0
SiteGround Inconsistency Prover: 1.0
SMTP Mailer: 1.0.5
Software Licensing and Restrict Content: 
Transients Manager: 1.7.4
User Switching: 1.3.0
WP Crontrol: 1.6.2
Write to the debug log in wp-content: 1.6
Yoast SEO: 6.1.1 (needs update - 7.0.3)

-- Network Active Plugins

Easy Digital Downloads: 2.8.10
SendGrid: 1.11.7
Show Site Number: 1.0.0
User Switching: 1.3.0

-- Webserver Configuration

PHP Version:              7.0.3
MySQL Version:            5.5.55
Webserver Info:           Apache/2.4.10 (Debian)

-- PHP Configuration

Memory Limit:             256M
Upload Max Size:          1000M
Post Max Size:            1000M
Upload Max Filesize:      1000M
Time Limit:               900
Max Input Vars:           3000
Display Errors:           On (1)
PHP Arg Separator:        &

-- PHP Extensions

cURL:                     Supported
fsockopen:                Supported
SOAP Client:              Installed
Suhosin:                  Not Installed

-- Session Configuration

EDD Use Sessions:         Enabled
Session:                  Enabled
Session Name:             PHPSESSID
Cookie Path:              /
Save Path:                
Use Cookies:              On
Use Only Cookies:         On

### End System Info ###

**Comment by mintplugins** [comment]
Nevermind me....this was because the file I was downloading had no files attached to it, so there was nothing to download. Thus, it redirected to purchase confirmation.
