### ISSUE TITLE
Feature Request: Show loading/processing graphic on submit button

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-free-downloads#26]
Not a bad idea: https://secure.helpscout.net/conversation/123306690/17450/

**Comment by pippinsplugins** [comment]
The submit button should be disabled after it is clicked to prevent against multiple clicks.

**Comment by mindctrl** [comment]
The commit for this affects all buttons on the page. They all spin.

![image](https://cloud.githubusercontent.com/assets/1254870/10176496/17a70a8a-66c3-11e5-8301-aee730bec3ba.png)

**Comment by SDavisMedia** [comment]
@ghost1227 I watched this clip of the behavior: http://cl.ly/1n3W07310C1m Got a few questions/issue.

1. @mindctrl just pointed one out while I was typing this. :) When you first click the purchase form button, the loading icon shouldn't show just yet. Not until the form is submitted.

2. Any reason why we don't use the loading icon that EDD buttons already use? I feel like it's a cleaner icon and also supports consistency.

3. Can we do anything about the button size collapsing to that of the icon? With default EDD buttons, the button size remains constant while the loading icon is there and doesn't change sizes until "checkout" is displayed.

**Comment by ghost1227** [comment]
@SDavisMedia Try it now

**Comment by mindctrl** [comment]
I think the spinner action should happen on the button in the modal instead of closing the modal and spinning the 'Download Now' button that opened the modal.

**Comment by ghost1227** [comment]
It originally did... I added closing the modal a version or two ago, can't remember why though. If @SDavisMedia agrees, I'll go ahead and switch it back.

**Comment by pippinsplugins** [comment]
@ghost1227 Can we have it on the `Download Now` button and leave the modal open?

**Comment by SDavisMedia** [comment]
@ghost1227 I definitely agree with the guys. I like the modal staying open with the graphic on that button.

**Comment by ghost1227** [comment]
@SDavisMedia @pippinsplugins I've moved it to the `Download Now` button and prevented the modal from closing but that causes two more problems. First, the user still has the ability to manually close the modal on their own. Second, there's no way for me to close the modal when the download completes!

**Comment by ghost1227** [comment]
@pippinsplugins @SDavisMedia ping?

**Comment by mindctrl** [comment]
@ghost1227 what about this? in `edd-free-downloads.js` add `delayClose: 2000` (or whatever number feels right) where you load jBox (around line 20), and then `newModal.close();` around line 142?

**Comment by SDavisMedia** [comment]
Gonna test now.

**Comment by SDavisMedia** [comment]
I like what's going on in the `issue/26` branch @mindctrl made. `delayClose: 2000` has been a little short for me. If the setting is checked for redirect after download, the modal can stay open until the page redirects. If it's not checked, I think it could be a tad longer. That's a tough one.

As for the user being able to close the modal while it's loading, I honestly don't feel like that's our problem. The button says to way and the loading icon is showing. If they start clicking around, it won't prevent everything from running. That's just my opinion, though.

**Comment by ghost1227** [comment]
@SDavisMedia The current iteration with the suggestions made by @mindctrl is in the currently staged changes for 1.1.0. I'm relatively happy with it, you've all said your peace... lets see what the users think!
