### ISSUE TITLE
Clear cart and fees when processing a free download

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-free-downloads#260]
To illustrate why this should happen, follow these steps:

1. Create a Discounts Pro discount that applies to a product in your store.
2. Add that product to the cart and verify that the Discounts Pro discount (negative fee) appears on the cart. Do not complete your purchase.
3. Now go to a free product that uses Free Downloads. Open the modal and "purchase" this product.

You get the following purchase data:

<img width="1200" alt="screenshot 2018-03-26 15 15 42" src="https://user-images.githubusercontent.com/2359131/37935987-9410920a-3108-11e8-8756-e65ae5ad92f1.png">

That's a free product with a negative fee. Obviously, that fee has nothing to do with the free product. It's coming from the product added to the cart in step 2.

**Comment by pippinsplugins** [comment]
PR ready for testing.

**Comment by SDavisMedia** [comment]
That'll do it. Works correctly for me. :+1:
