### ISSUE TITLE
No File Download Link in the Email [Free Purchase]

### ISSUE THREAD

**Issue by samsono** [easydigitaldownloads/edd-free-downloads#262]
I am using an email option to send the download link,
But sometimes the email has no download link at all, This issue happening regularly.
Kindly Suggest me to fix this issue.

Thanks
Sam

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
