### ISSUE TITLE
Opt-in checkbox must be unchecked by default

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-free-downloads#263]
In order to comply with anti-spam laws in Canada and GDPR-type laws in the EU, opt-in checkboxes must be unchecked by default.

![uncked-by-default](https://user-images.githubusercontent.com/1638128/38255577-26e6eaf8-372a-11e8-87eb-cc9cd6a9a7eb.jpg)

**Comment by cklosowski** [comment]
So looking at this i'm not sure there is proper support for this in all the add-ons. I'll make a specific setting for Free Downloads, that is list independent.

**Comment by SDavisMedia** [comment]
All's working well for me. :+1:
