### ISSUE TITLE
Add Privacy Policy checkbox to Free Downloads

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-free-downloads#264]
Since EDD is looking to add a Privacy Policy checkbox to checkout. Free Downloads will still have to do the same, since it loads it's own interface.

**Comment by cklosowski** [comment]
This will have to be in place once the Checkbox is added to EDD core.

**Comment by cklosowski** [comment]
## Testing Note

You will need to be on the latest `master` of EDD to enable this option. Version 2.9.1 or later.

**Comment by SDavisMedia** [comment]
All components of the enhancement working perfectly for me. :+1:
