### ISSUE TITLE
Load js scripts in footer

### ISSUE THREAD

**Issue by dashkevych** [easydigitaldownloads/edd-free-downloads#267]
Is there any particular reason that **isMobile.min.js** and **edd-free-downloads.min.js** files are loaded in the header section of the site? Can we load them in the footer section (before /body tag)?

I've tried these changes, and it seems to work fine:

<pre>wp_register_script( 'edd-free-downloads-mobile', EDD_FREE_DOWNLOADS_URL . 'assets/js/isMobile'. $suffix . '.js', array( 'jquery' ), false, true );

wp_register_script( 'edd-free-downloads', EDD_FREE_DOWNLOADS_URL . 'assets/js/edd-free-downloads' . $suffix . '.js', array( 'jquery' ), EDD_FREE_DOWNLOADS_VER, true );</pre>

**Comment by cklosowski** [comment]
I don't see any specific reason why not. I'll give it a shot and do a bunch of testing to make sure we don't run into any conflicts. :+1: Thanks for the heads up @dashkevych

**Comment by cklosowski** [comment]
This could use some testing with multiple themes.

**Comment by SDavisMedia** [comment]
I'm not seeing any issues here. :+1:
