### ISSUE TITLE
Remove dependancy of Dashicons from the front end.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-free-downloads#268]
As it stands, Dashicons is only loaded on the front end for the `X` to close the modal. We should be able to find a way around having to load the entire Dashicons just for this.

Since Admin loads dashicons anyway, we don't have to worry about dependencies there.

**Comment by SDavisMedia** [comment]
Made some tweaks detailed on the PR. All good on my end. :+1: 

<img width="389" alt="screenshot 2018-04-10 21 39 52" src="https://user-images.githubusercontent.com/2359131/38596684-c50192d2-3d07-11e8-8ee2-628f51b0e766.png">
