### ISSUE TITLE
On Mobile, with email verification enabled, JSON/AJAX page is loaded/shown instead of returned

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-free-downloads#276]
On mobile, if you have email verification enabled, the JSON success (which is intended to be returned via AJAX) is actually shown to the user directly. So it looks like this:

<img width="1440" alt="screen shot 2018-05-02 at 12 27 05 pm" src="https://user-images.githubusercontent.com/1638128/39536299-2c305c7e-4e04-11e8-9a65-3a0b29ddcc69.png">

Instead of how it should look which is like this (on desktop where it is working properly):
<img width="1437" alt="screen shot 2018-05-02 at 12 28 47 pm" src="https://user-images.githubusercontent.com/1638128/39536369-64d7b0d6-4e04-11e8-8bed-09a34e25822a.png">

**Comment by mintplugins** [comment]
Customer ticket:
https://secure.helpscout.net/conversation/569560866/81184/

**Comment by pippinsplugins** [comment]
@mintplugins could you look into fixing this today please?

**Comment by pippinsplugins** [comment]
Another report: https://secure.helpscout.net/conversation/578524994/81958?folderId=180499

**Comment by mintplugins** [comment]
This is ready for testing. 

Replication steps:
1. Enable email verification in the Free Downloads settings
2. Put your browser in mobile mode (see screenshots above)
3. Attempt to download the file
4. You should see raw JSON on the screen

Switch to `issue/276`

1. Repeat above steps. You should now see the email verification note on the form. 

Additional tests to make sure nothing broke:
1. Test in non mobile view to make sure it works properly on desktop
2. Test with email verification off to make sure it works on desktop and mobile as expected. 

I have tested all of the above on my end and it is all working as expected.

**Comment by SDavisMedia** [comment]
Replicated on `master`.

On `issue/276`, it fixes that problem but I believe it broke **Mobile On-Complete Handler**. From both my phone and my browser mobile view, submitting the download form just sends me back to the product page. I've confirmed that on `master`, this is not the case. For example, if I chose Purchase Confirmation for the **Mobile On-Complete Handler**, I'm properly sent there.

**Comment by SDavisMedia** [comment]
This is with email verification disabled.

**Comment by SDavisMedia** [comment]
Working well for me now thanks to: https://github.com/easydigitaldownloads/edd-free-downloads/pull/280/commits/2a1e04da53cd59c70df175de1fd394347b42af37

All good here. :+1:
