### ISSUE TITLE
Support for Bundles

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-free-downloads#28]
Is there any particular reason why it can't support bundles? I think this would be a good enhancement.

**Comment by SDavisMedia** [comment]
Nope. At least give a reason.

**Comment by mindctrl** [comment]
Would love to see this supported. Lots of good use cases for supporting bundles. Seems like an easy fix for sites that don't have auto-download enabled. Any particular reason why it's not supported @ghost1227?

**Comment by pippinsplugins** [comment]
:+1:

**Comment by ghost1227** [comment]
Because when I originally wrote FD I couldn't find an easy way to support bundles or variations. Variations are now supported... guess it's time to focus on bundles! Thanks for the reminder.

**Comment by ghost1227** [comment]
Ironically, the 2.0.0 update for auto-download makes part of this issue a LOT easier. However, I'm still not 100% sure the best way to implement this. If a bundle is free AND all items in it are free, then it's straightforward. Similarly, if a bundle is free and an archive URL is provided (new feature in 2.0.0), it's straightforward. However, if a bundle is free, no archive URL is provided, and items in the bundle are NOT free, the system will break. The download system still significantly depends on item price being $0.00, so when gathering the download items for child products, it'll fail if a child product isn't free.

**Comment by SDavisMedia** [comment]
My first thought is to say it shouldn't support a free bundle that includes paid items. Free Downloads is designed to work for free downloads so I think we have a good argument for saying it won't work for paid bundle items, even if a person or two disagrees.

**Comment by ghost1227** [comment]
@SDavisMedia That's where I'm torn. Technically, the bundle IS free, so it's possible that they intend to include paid items in a free bundle (no matter how stupid it sounds). I can tweak the logic to make it work in that situation, but I'm not sure if I SHOULD

**Comment by SDavisMedia** [comment]
Right, that's exactly where I stand. It could be done but I think there's a good case for not supporting it.

**Comment by ghost1227** [comment]
The alternative is that we could make it an option... disallow it by default, but have an option to enable paid items in free bundles being treated as free.

**Comment by SDavisMedia** [comment]
Maybe a setting that appears in the free bundle's meta box in an obvious notice only when a paid item gets added to the bundle?

**Comment by ghost1227** [comment]
Free Downloads settings are now in a dedicated meta box (not under Download Options anymore), so we can certainly add a setting there for it which only appears if product type == bundle && child product total value > 0

**Comment by ghost1227** [comment]
This is getting listed as wont-fix for the time being. I've got a prototype working for bundle support, but it ONLY works post-save. Since the EDD add/edit product metabox is using Chosen, the normal selectors for detecting select box status change don't work, and the Chosen docs don't indicate any way to dynamically detect change. As such, we have no way of updating this on-the-fly, which makes support for bundles awkward at best. I'd rather explicitly not support them, than have partial support which is confusing for users. If I can find a way of detecting Chosen status change (or if someone points a way out) I'll revisit this issue.

**Comment by pippinsplugins** [comment]
Re-opening.

Just had another request come in and made me think about it a bit.

I really don't think we should be bothering ourselves with what the price of the items inside a bundle are. That's not our concern.

In core, we let site admins set a price on a bundle. This price is in no way tied to the price of the items inside the bundle. Why should Free Downloads be any different?

Obviously it's weird and silly to make a free bundle that includes paid items, but hey, people want weird things.

I vote we add bundle support and make it work exactly like free downloads of normal products.

Newest request: https://secure.helpscout.net/conversation/254215064/42987/?folderId=180499

**Comment by ghost1227** [comment]
I saw that come in. Argued with myself about whether or not to re-open. My issue with it isn't about the pricing... we'd already decided to work around it. My problem is that I can't find a way to make it work on the backend. Read my last comment (when I closed it)

**Comment by pippinsplugins** [comment]
I don't see why it's an issue on the backend . . . just show the options if the bundle box is checked. Nothing else really needs to change.

**Comment by ghost1227** [comment]
Just for my own reference when I start working on this again... we're changing our outlook on it. Bundles will _always_ be supported. If the bundle option is checked, we're allowing FD support, regardless of the value of the items in the bundle. Once this goes live, we also have to update the docs to outline how this works so users don't get surprised by FD downloading paid products for free.

**Comment by ghost1227** [comment]
This has been added in 2.0.0
