### ISSUE TITLE
JS issue: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by dashkevych** [easydigitaldownloads/edd-free-downloads#281]
This JS issue appears when the "Enable variable pricing" option is enabled and the product has several pricing options. 

Try to switch price options in the front end to see the issue: https://snag.gy/htnBPW.jpg

**Comment by dashkevych** [comment]
Yes, I am using version 2.3.1. You can see it from the screenshot in the first message. 
I've also switched to a default WordPress theme (twenty seventeen), and I am getting the same issue. Here is a screenshot: https://snag.gy/DgHKLZ.jpg

EDD version is 2.9.1

**Comment by pippinsplugins** [comment]
I've tried to replicate this but so far cannot make it happen.

**Comment by dashkevych** [comment]
I've deactivated all the plugins, and just left EDD and EDD Free Downloads plugins active, and still see the issue. It looks it appears only for logged-in users when the "Check to bypass the modal if a user is logged in." option is enabled.

Also, please check Ticket 82457 (sent via EDD site). It seems like it's possible to bypass checkout process when this extension is active.

**Comment by pippinsplugins** [comment]
Tracked it down.
