### ISSUE TITLE
Internal error when submitting an empty email address in modal

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-free-downloads#36]
[Customer reported](https://secure.helpscout.net/conversation/141519016/21854/?folderId=180499) that when submitting the form without supplying an email address, you get a message that says "An internal error occurred, please try again or contact support."

Replicated locally. Screencast: http://cl.ly/43061G0G350z

**Comment by SDavisMedia** [comment]
Just got another case for this. I also replicated locally. @ghost1227 Can you take a look at this today?

**Comment by SDavisMedia** [comment]
I get the same behavior when an email address format is invalid.

With both situations, it appears that an error message attempts to display right there on the form. So no need to wp_die().

**Comment by pippinsplugins** [comment]
@ghost1227 can we please get this fixed?

**Comment by SDavisMedia** [comment]
Got another case.

**Comment by mindctrl** [comment]
@SDavisMedia proposed fix in `issue/36`.

**Comment by SDavisMedia** [comment]
@mindctrl When I tested, it disabled the submit button properly but once I entered the necessary information, it was still disabled.

That said, the original form is throwing errors just fine when the submit button is clicked and a required or necessary field does not have a value. The problem is the wp_die() that happens right after it. It seems to me like simply not dying is the answer.

**Comment by mindctrl** [comment]
@SDavisMedia maybe sounds like cached JS if it didn't enable the submit button for you? Not seeing that here. What steps did you take that keep the button disabled?

Basically went this route because there's no need to even allow submission if the email is empty or invalid, which should prevent that wp_die message from kicking off.

**Comment by SDavisMedia** [comment]
@mindctrl I basically tested with all form field scenarios. Requiring just email... requiring name and email... having the name fields but not requiring them. The submit button is getting disabled but then when I fix my errors (which I think should show on the form), clicking the submit button again still will not allow me to submit.

Also I just noticed that even when I click the disabled submit button, I can see the cart widget actually adding the item to the cart... though the cart is actually still empty if I close the modal and go to it.

**Comment by SDavisMedia** [comment]
Works perfectly. :ok_hand:
