### ISSUE TITLE
Doesn't support 'text link' option in [purchase_link] shortcode

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-free-downloads#40]
Free Downloads overrides the form and doesn't abide by the link style setting for purchase links. It always shows a button.

Example: `[purchase_link id="3164" style="text link" color="" text="I want a text link"]`

Customer reported and confirmed locally.

**Comment by pippinsplugins** [comment]
@ghost1227 could you take care of this?

**Comment by ghost1227** [comment]
@pippinsplugins Yep! Completely forgot about that option. May not get to it until Saturday due to the holiday.

**Comment by ghost1227** [comment]
Fixed with https://github.com/easydigitaldownloads/edd-free-downloads/pull/83
