### ISSUE TITLE
Safari bug with Mailchimp optin

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-free-downloads#48]
When the opt-in is shown on the free downloads modal, the checkbox for opt-ing in doesn't show in Safari:
![screen shot 2016-01-22 at 4 08 17 pm](https://cloud.githubusercontent.com/assets/1390124/12525583/85f9babe-c122-11e5-8931-4ec253339e70.png)

I've tested both Chrome and Firefox and it all seems to work fine.

**Comment by ghost1227** [comment]
I'm not sure if this was fixed with the move to using template files, or if I fixed it at some point and forgot to close the issue, but I can't replicate this now. If you're still seeing it, feel free to reopen.
