### ISSUE TITLE
Compatibility with Auto Register add-on

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/edd-free-downloads#49]
We set up Free Downloads on AffiliateWP but ran into an issue. We use the Auto Register plugin and so each time you enter your email address into the form and download a free download, it auto creates a user account on the site.

We should add an option to disable user accounts in Auto Register
https://github.com/easydigitaldownloads/edd-auto-register

**Comment by pippinsplugins** [comment]
@ghost1227 Think you could put this in?

**Comment by sumobi** [comment]
@pippinsplugins Here's a solution:
https://github.com/AffiliateWP/affwp-functionality/blob/master/affwp-functionality.php#L304-L313

Short-circuits auto register for free downloads. @ghost1227 maybe you could add a setting in the admin that does the same when Auto Register is active.

**Comment by ghost1227** [comment]
Yep! Question though... isn't having the same function in both plugins kinda redundant? Or am I missing what you're saying @sumobi?

**Comment by pippinsplugins** [comment]
@ghost1227 Andrew is just asking if we could have an option to disable Auto Register in Free Downloads. At the moment, if Auto Register and Free Downloads are both active, everyone that submits their name/email will get an account created. It would be nice to have an option to disable auto register for free downloads but keep it for regular purchases.

**Comment by ghost1227** [comment]
Gotcha. Can do!

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sumobi** [comment]
Awesome :+1:

**Comment by ghost1227** [comment]
Missed this issue. This was added in 1.1.0
