### ISSUE TITLE
Support for variable pricing

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-free-downloads#5]
I do think it's possible that a user would configure a download to have variable pricing but all price options are $0.00. They might do it just to separate download files. 

Free Downloads doesn't seem to support this. Should it?

**Comment by ghost1227** [comment]
Ehhhhh... Maybe. Gimme a viable use case and I'll add it.

**Comment by pippinsplugins** [comment]
That'd be magnificent

**Comment by pippinsplugins** [comment]
Shouldn't be hard to do it.

**Comment by pippinsplugins** [comment]
Viable use case is super simple: people want to have a product with
multiple price options. If some one chooses the free option, checkout
should be skipped.

As simple as that.

**Comment by SDavisMedia** [comment]
@ghost1227 I already did.

**Comment by ghost1227** [comment]
@pippinsplugins is there a good way of updating the 'checkout' button label if a free product is selected? That's the biggest reason I never included it...

**Comment by pippinsplugins** [comment]
Simple custom javascript

**Comment by mindctrl** [comment]
Another request for this.

**Comment by SDavisMedia** [comment]
Got another request. Refund pending.

**Comment by SDavisMedia** [comment]
Another request. https://secure.helpscout.net/conversation/140079199/21493/?folderId=180499
