### ISSUE TITLE
Bug when used with FacetWP

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/edd-free-downloads#50]
When a FacetWP is used to filter a list of downloads it does so using Ajax. After a filter has been applied, the Download Now button does nothing on click. Loading the page directly with the filters set in the URL results in everything working as expected. Just when a filter is applied and the results adjust via Ajax.

**Comment by ghost1227** [comment]
@brashrebel Can you post the display code you're using for the facet template?

**Comment by ghost1227** [comment]
Since we haven't gotten a response, and the bug has been fixed with my (admittedly minimal) FacetWP tests, I'm going to close this issue. If it isn't fixed with the newest release (or master branch here), feel free to reopen.

**Comment by mintplugins** [comment]
This appears to still be an issue. @ghost1227 A customer has given us permission to investigate this with their installation including FacetWP here: https://secure.helpscout.net/conversation/199122995/33509/?folderId=749231

**Comment by ghost1227** [comment]
Yay! Finally a real test site!

**Comment by mintplugins** [comment]
@ghost1227 Yes! Are you able to check that out?

**Comment by ghost1227** [comment]
Yep!

**Comment by mintplugins** [comment]
Great - let me know when you have a chance to take a look and I'll update the customer

**Comment by mintplugins** [comment]
@ghost1227 This customer has 3 tickets open about this right now and keeps opening new ones.

**Comment by ghost1227** [comment]
@mintplugins Spent most of the night working on it... haven't figured out how to make the two play nice. Any thoughts wouldn't go amiss right about now!

**Comment by ghost1227** [comment]
I've tried every way of handling the selector I can think of... some of them stupid specific. It seems like what we originally posited was the error isn't quite what we thought... the way FacetWP works with AJAX is resulting in an issue... seems to me that we'd have to re-run the FD script every time FacetWP runs... but I can't figure out a way to do it.

**Comment by spencerfinnell** [comment]
You can use https://facetwp.com/documentation/facetwp-loaded/ if you need to reinitialize anything after a change is made.

**Comment by mintplugins** [comment]
@ghost1227 I'm sure you did this already but I've had success with ajax and selectors continuing to work after ajax updates in the past if I use 

`$(document).on(`

As opposed to 

`$('body').on(`

**Comment by ghost1227** [comment]
I've switched this to use `$(document.body)` and it seems to be working. Again, I'm not great with FacetWP so I'd appreciate someone else taking a look at it. The changes are merged into the `release/2.0.0` branch and will be going live whether or not it actually fixes this issue because using `$(document.body)` over `$('body')` has proven to be more efficient.
