### ISSUE TITLE
Support for variable pricing + multi purchase mode

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/edd-free-downloads#52]
#43 got this close but there's still one aspect of variable pricing that does not work properly. If a download has variable prices, all prices are free, unique files assigned to each variation and multi purchase mode on, then "purchasing" more than one variation at the same time results in the products in the purchase receipt email and on the purchase confirmation page to show "No downloadable files found.".

In case you're curious, the use case which discovered this is an image download where the variations are the different sizes of the image. In some cases users may want more than one size at the same time.

**Comment by ghost1227** [comment]
Fixed in 1.2.8 (pending)

**Comment by SDavisMedia** [comment]
Fixed. Thanks!
