### ISSUE TITLE
MailChimp subscriptions not working when not using download-specific lists

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-free-downloads#53]
When the MailChimp opt-in is enabled and only the global list option is selected for MailChimp, subscriptions to MailChimp are not processed.

It works fine when a download-specific list is enabled.

**Comment by ghost1227** [comment]
Fixed with #87

**Comment by SDavisMedia** [comment]
Replicated and confirmed fixed.
