### ISSUE TITLE
Add HTML support to notes field

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-free-downloads#56]
We've had a request for HTML support in the notes field: https://secure.helpscout.net/conversation/194704987/32720/?folderId=180499

Makes sense to me.

**Comment by pippinsplugins** [comment]
See https://github.com/easydigitaldownloads/edd-free-downloads/pull/58/files#r60848809

**Comment by ghost1227** [comment]
Fixed

**Comment by pippinsplugins** [comment]
@ghost1227 It's still a P tag: https://github.com/easydigitaldownloads/edd-free-downloads/blob/master/includes/actions.php#L155

**Comment by ghost1227** [comment]
@pippinsplugins I'll leave it open until I re-merge. I didn't want to do the merge until I was sure the other issue was fixed as well.

**Comment by pippinsplugins** [comment]
@ghost1227 I'm missing something. Where's the fix for it? I don't see any commits.

**Comment by ghost1227** [comment]
@pippinsplugins https://github.com/easydigitaldownloads/edd-free-downloads/blob/master/includes/actions.php#L155 I don't work on this repo. I have forks on my account where I do the actual dev, then merge the changes when they're done. Just merged this one to make you happy

**Comment by pippinsplugins** [comment]
@ghost1227 Okay. Is everything merged in now and ready to review again?
