### ISSUE TITLE
Free Downloads evaluates paid variable pricing items as free when no download ID is passed

### ISSUE THREAD

**Issue by themotionclub** [easydigitaldownloads/edd-free-downloads#66]
Issue with Easy Digital Downloads - Free Downloads v1.2.1 tested with current system set-up EDD 2.5.15 and wordpress 4.5.2

Potentially subject issue can allow to download any item free of charge, although they are sold for money.
Here is the issue provided step by step using screenshots:

When you do the following, Go to product (download) page, view page source, search for free-download and you will find something like this: ?edd-free-download=true&download_id=1665, append that part to download page link and go to combined link, the page will request to provide e-mail, name and surname, and after submitting the form, it will go to purchase confirmation page and provide a link to download the resource free of charge. My product has variable pricing option enabled, but the system doesn't check that. I just disabled free-downloads plugin so you will not be able to replicate that on the website provided in screenshot.

Hope this will help to fix this issue.
Thanks,

_note_
*remove photos once I replicated - Chris K*

**Comment by mindctrl** [comment]
Fix works for me here.

**Comment by mintplugins** [comment]
Fix works here as well.

**Comment by mindctrl** [comment]
Thanks for reporting this @themotionclub

**Comment by themotionclub** [comment]
Thank You too, glad to help with this.
