### ISSUE TITLE
Checkbox for email receipt doesn't work with Receipful

### ISSUE THREAD

**Issue by fxbenard** [easydigitaldownloads/edd-free-downloads#71]
Even with the checkbox checked not to receive email, an email is sent after download.

Not sure you can do anything about it, but at least now you know.

![2016-07-08_00-17-49](https://cloud.githubusercontent.com/assets/802114/16671805/f2f7cafe-44a1-11e6-86c0-1168ba8c6895.png)

![2016-07-08_00-24-42](https://cloud.githubusercontent.com/assets/802114/16671861/699b8b0a-44a2-11e6-859b-64efab625c3b.png)

**Comment by pippinsplugins** [comment]
@ghost1227 Could you look into this please?

**Comment by ghost1227** [comment]
@fxbenard The way our option works is by removing the action that triggers EDD sending emails. It looks like Receiptful is doing the same thing, then adds in their own system. I think I can bypass it, but I'll need help from someone familiar with Receiptful for testing purposes. Any interest?

**Comment by fxbenard** [comment]
@ghost1227 For sure, how can I help?

**Comment by ghost1227** [comment]
@fxbenard I'm just not super familiar with Receiptful, so I'd like someone who actually IS to test a beta before I push it.

**Comment by fxbenard** [comment]
Send it over, I'll give it a try. A branch to test?

**Comment by ghost1227** [comment]
My initial test failed, but I sent an email to Receiptful to see if they'd work with me to expose a global or define a filter that I can work with. Stay tuned!

**Comment by ghost1227** [comment]
Got a response from Receiptful. They no longer support the plugin on .org. I'm trying to get them to transfer it to me/EDD rather than pulling it from the repo. If they do pull it, I'll look at writing a new plugin (or forking the last version of theirs)

**Comment by michaelbeil** [comment]
Sounds like a plan @ghost1227.

**Comment by ghost1227** [comment]
Fixed in 1.2.5
