### ISSUE TITLE
Introduce a hook to allow for additional output

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-free-downloads#74]
If someone wants to add their own fields - or something like a Google reCaptcha to the Free Downloads modal, there aren't currently any hooks to allow them to do that. 

**Proposal:**
Add an action hook somewhere in the edd_free_downloads_display_inline function to allow for additional output.

**Comment by ghost1227** [comment]
Eight new hooks added in 1.2.5 (four for inline, four for redirect)
