### ISSUE TITLE
Free download button disappears after being clicked

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/edd-free-downloads#79]
When clicking the "Free download" button, the modal pops up and then the button disappears underneath. This seems to have been introduced in 1.2.7.

![screen shot 2016-08-29 at 2 50 37 pm](https://cloud.githubusercontent.com/assets/52581/18039531/0e3eb2da-6df8-11e6-84e6-7e72f8e5fa85.png)

no button:

![screen shot 2016-08-29 at 2 50 47 pm](https://cloud.githubusercontent.com/assets/52581/18039530/0e3c1de0-6df8-11e6-8914-536d64ed7ab6.png)

![screen shot 2016-08-29 at 2 52 49 pm](https://cloud.githubusercontent.com/assets/52581/18039553/4a494466-6df8-11e6-9c67-9172a9480591.png)

**Comment by ghost1227** [comment]
Fixed in 1.2.8 (pending)

**Comment by pippinsplugins** [comment]
See https://trello.com/c/Pg8cngiR/561-free-downloads

**Comment by michaelbeil** [comment]
This was fixed in 1.2.8 which got moved to `release/2.0.0`.
