### ISSUE TITLE
Custom buttons for download now

### ISSUE THREAD

**Issue by michaelbeil** [easydigitaldownloads/edd-free-downloads#80]
At this time we do not have an option for using custom buttons (without a shortcode) with Free Downloads. It would be great to make this available.

> I use my own button / graphic. Not a short code. That works fine for regular purchases with the Urls I posted. But not for free stuff where I use that free download plugin.

Reference: https://secure.helpscout.net/conversation/243871564/0/?folderId=180504

**Comment by ghost1227** [comment]
This was already possible, just not well documented. I've made it a bit easier with 1.2.8. All you have to do is this:

`<a href="#edd-free-download-modal" class="edd-free-download" data-download-id="{download_id}">Link</a>`

**Comment by pippinsplugins** [comment]
@ghost1227 can you please get it documented?

**Comment by ghost1227** [comment]
@pippinsplugins Added a simpler way to add custom links through a new `edd_free_download` shortcode. Both the shortcode and manual creation of FD-compatible links are also now documented in a new HS page "Free Downloads - Advanced Usage"

**Comment by pippinsplugins** [comment]
Great!

**Comment by ghost1227** [comment]
@pippinsplugins The relevant release is on a 24-hour hold. I got inspired by a customer request and started a bit of a larger overhaul of FD... 1.2.8 may well become 1.3.0!
