### ISSUE TITLE
The new zip file support fails with remotely hosted files

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/edd-free-downloads#85]
Using the new direct download compression option, if files are hosted off-site, they fail to be added to the zip file before download.

**Comment by ghost1227** [comment]
Fixed in 2.0.0

**Comment by pippinsplugins** [comment]
Link commit messages please.

**Comment by ghost1227** [comment]
https://github.com/easydigitaldownloads/edd-free-downloads/commit/d6e930070a8704ede750ffce3290d6ab8b26303c

**Comment by michaelbeil** [comment]
In https://github.com/easydigitaldownloads/edd-free-downloads/pull/83

**Comment by blackPantherOS** [comment]
Hi! Remote files compression is fail, I get multiple 0B files in a zip file.
