### ISSUE TITLE
Add per-download notes

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/edd-free-downloads#94]
In 2.0.0 I intended to add support for overriding the global notes field per-download, but it didn't make it in. Let's make this happen in 2.1.0!

**Comment by mintplugins** [comment]
Working great for me. Global is used if notes are enabled. They are over-ridden by the note in the product itself if used.

**Comment by ghost1227** [comment]
Woot! That was a pain to write (it did result in much better code though).
