### ISSUE TITLE
Support the text parameter in purchase_link shortcode

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-free-downloads#98]
Free Downloads supposed the `[purchase_link]` shortcode but you cannot override the button text. It will always use the text specified in the Free Downloads settings.

It should display whatever is entered in the `text` parameter. This is pretty much a continuation from https://github.com/easydigitaldownloads/edd-free-downloads/issues/40, which I believe the original user was trying to do anyway.

**Comment by ghost1227** [comment]
@SDavisMedia Just did some digging and as far as I can tell, it's not actually possible at the moment. The EDD `[purchase_link]` shortcode compiles a bunch of args and passes them to the `edd_get_purchase_link()` function, which results in the same output as if the purchase link was being displayed in the download list or an individual page. There's no way to differentiate between a purchase link added via shortcode, and one in the download list, so there's nothing for me to target to tell the system to ignore the FD button text and use the shortcode's. Maybe we should look at adding a class through the core shortcode to identify the purchase link as being shortcode-generated?

**Comment by SDavisMedia** [comment]
Not sure. You'd have to talk to one of the devs about that.

Either that or enhance the new `[edd_free_download]` to be able to output as a button. Would be as simple as adding another accepted parameter that defaults to its current state or accepts a value that adds the necessary classes to the link so it mimics an EDD button.

**Comment by ghost1227** [comment]
It _should_ work with the default purchase link shortcode... that's what users will expect. @pippinsplugins thoughts?

**Comment by pippinsplugins** [comment]
@ghost1227 any reason you can't use the `edd_purchase_link_args` filter?

**Comment by ghost1227** [comment]
@pippinsplugins Because I can't differentiate between shorcode-based and non-shortcode purchase buttons using that (that i can find). We need all non-shortcode buttons to use the default label set in FD settings, but we want to allow users to override that through the `text` param in the `[purchase_link]` shortcode... but since the shortcode passes an array to the function that's really no different than what the purchase list does, for example, we have no way of deciding whether or not to _allow_ that override.

**Comment by pippinsplugins** [comment]
Yes you can.

Look at the value of the `text` key. If it's different than the store-wide setting, it's been set on the shortcode.

**Comment by ghost1227** [comment]
Ooh! Clever! I never even thought of that! Thanks!

**Comment by mintplugins** [comment]
I can enter custom text using:

 [purchase_link text="MY CUSTOM TEXT"]

However, if using the popup modal, when it pops up, the button text changes back to "DOWNLOAD NOW". It should probably remain with my custom text if at all possible (I think).

**Comment by ghost1227** [comment]
It wasn't intended to... @pippinsplugins thoughts?

**Comment by pippinsplugins** [comment]
Yes it should change back. The button should always, before and after click, show the custom text entered.

**Comment by ghost1227** [comment]
@pippinsplugins i you're misunderstanding him. he means that the second download button IN the modal shows the download text, not that the main button reverts to 'Download Now' after it's clicked

**Comment by ghost1227** [comment]
...though the answer could very well be the same

**Comment by pippinsplugins** [comment]
Ok I'm bit confused but here's how it should work in my opinion:

1. Text set in [purchase_link] should show on the button that opens the modal
2. Button inside modal should be unaffected by [purchase_link]

**Comment by ghost1227** [comment]
Actually... both comments are valid. it IS reverting to download now >_<

**Comment by mintplugins** [comment]
I don't know if I was clear enough. Sorry about that. I'm talking about the text on the button itself - it reverts to "DOWNLOAD NOW" after I click it

![purchase-text](https://cloud.githubusercontent.com/assets/1638128/19158433/ade372fe-8bb6-11e6-877b-bb8635a2dd8e.jpg)

**Comment by ghost1227** [comment]
@mintplugins it's all good, I misunderstood what you were saying. Finally figured it out when I went to grab a screenshot to demonstrate what I _thought_ you were saying

**Comment by ghost1227** [comment]
@mintplugins there you go. simple fix

**Comment by mintplugins** [comment]
Perfect. Working now!

**Comment by ghost1227** [comment]
@mintplugins no more issues? good to close?

**Comment by mintplugins** [comment]
Yeah looks good to me. I say we merge it in and close.
